import type { TriviaContentItem } from "../types";

export const ENTERTAINMENT: TriviaContentItem[] = [
  { id: "en-ent-001", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "Name a movie in the Marvel Cinematic Universe.", acceptedAnswers: ["avengers", "iron man", "thor", "black panther", "spider-man", "spiderman", "captain america", "doctor strange", "ant-man"] },
  { id: "en-ent-002", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "Who directed the movie 'Titanic'?", acceptedAnswers: ["james cameron"] },
  { id: "en-ent-003", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "What company produces the Toy Story movies?", acceptedAnswers: ["pixar", "disney"] },
  { id: "en-ent-004", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "Name an instrument found in a typical orchestra.", acceptedAnswers: ["violin", "cello", "flute", "trumpet", "piano", "clarinet", "oboe", "viola", "trombone", "drums", "harp"] },
  { id: "en-ent-005", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "What is the name of the wizard school in the Harry Potter series?", acceptedAnswers: ["hogwarts"] },
  { id: "en-ent-006", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "Which streaming service produced the show 'Stranger Things'?", acceptedAnswers: ["netflix"] },
  { id: "en-ent-007", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "Name a Disney princess.", acceptedAnswers: ["cinderella", "snow white", "belle", "ariel", "jasmine", "aurora", "mulan", "rapunzel", "moana", "tiana"] },
  { id: "en-ent-008", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "What color is Spider-Man's suit, mainly?", acceptedAnswers: ["red", "red and blue"] },
  { id: "en-ent-009", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "Who played Jack in the movie 'Titanic'?", acceptedAnswers: ["leonardo dicaprio", "dicaprio"] },
  { id: "en-ent-010", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "Name the singer known as the 'King of Pop'.", acceptedAnswers: ["michael jackson"] },
  { id: "en-ent-011", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "What is the highest-grossing film of all time (unadjusted for inflation) as of the early 2020s?", acceptedAnswers: ["avatar"] },
  { id: "en-ent-012", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "Who composed the score for 'Star Wars'?", acceptedAnswers: ["john williams"] },
  { id: "en-ent-013", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "Which TV series follows the Stark, Lannister, and Targaryen families?", acceptedAnswers: ["game of thrones"] },
  { id: "en-ent-014", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "Who directed the 'Inception' and 'Interstellar' films?", acceptedAnswers: ["christopher nolan"] },
  { id: "en-ent-015", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "What is the name of the coffee shop in the sitcom 'Friends'?", acceptedAnswers: ["central perk"] },
  { id: "en-ent-016", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "Which artist released the album '1989'?", acceptedAnswers: ["taylor swift"] },
  { id: "en-ent-017", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "What is the fictional African nation in 'Black Panther' called?", acceptedAnswers: ["wakanda"] },
  { id: "en-ent-018", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "Who is the author of the Harry Potter book series?", acceptedAnswers: ["j.k. rowling", "jk rowling", "rowling"] },
  { id: "en-ent-019", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "What animated studio made 'Frozen' and 'Moana'?", acceptedAnswers: ["disney", "walt disney animation"] },
  { id: "en-ent-020", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "In which city is the sitcom 'Friends' set?", acceptedAnswers: ["new york", "new york city", "nyc"] },
  { id: "en-ent-021", category: "ENTERTAINMENT", difficulty: "HARD", prompt: "Who won the Academy Award for Best Actor in 2020 for 'Joker'?", acceptedAnswers: ["joaquin phoenix"] },
  { id: "en-ent-022", category: "ENTERTAINMENT", difficulty: "HARD", prompt: "What was the first feature-length fully computer-animated film?", acceptedAnswers: ["toy story"] },
  { id: "en-ent-023", category: "ENTERTAINMENT", difficulty: "HARD", prompt: "Which film won the Academy Award for Best Picture in 2020?", acceptedAnswers: ["parasite"] },
  { id: "en-ent-024", category: "ENTERTAINMENT", difficulty: "HARD", prompt: "Who directed the original 'Star Wars' trilogy?", acceptedAnswers: ["george lucas"] },
  { id: "en-ent-025", category: "ENTERTAINMENT", difficulty: "HARD", prompt: "What was Queen's lead singer's real name?", acceptedAnswers: ["freddie mercury"] },
  { id: "en-ent-026", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "What kind of creature is Simba in 'The Lion King'?", acceptedAnswers: ["lion"] },
  { id: "en-ent-027", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "Name the yellow characters from the 'Despicable Me' movies.", acceptedAnswers: ["minions"] },
  { id: "en-ent-028", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "Which superhero is also known as the Dark Knight?", acceptedAnswers: ["batman"] },
  { id: "en-ent-029", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "What is the name of the fictional wizarding sport played on broomsticks?", acceptedAnswers: ["quidditch"] },
  { id: "en-ent-030", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "Who is the star of the 'John Wick' film series?", acceptedAnswers: ["keanu reeves"] },
];
