import type { TriviaContentItem } from "../types";

export const FOOD_CULTURE: TriviaContentItem[] = [
  { id: "en-foo-001", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "Name a dish that traditionally contains rice.", acceptedAnswers: ["biryani", "sushi", "paella", "risotto", "kabsa", "pilaf", "fried rice", "jollof rice"] },
  { id: "en-foo-002", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "What country is pizza traditionally from?", acceptedAnswers: ["italy"] },
  { id: "en-foo-003", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "What country is sushi traditionally from?", acceptedAnswers: ["japan"] },
  { id: "en-foo-004", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "What is the main ingredient in guacamole?", acceptedAnswers: ["avocado"] },
  { id: "en-foo-005", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "What grain is used to make bread?", acceptedAnswers: ["wheat", "flour"] },
  { id: "en-foo-006", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "What fruit is traditionally used to make wine?", acceptedAnswers: ["grapes", "grape"] },
  { id: "en-foo-007", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "What is the main ingredient in hummus?", acceptedAnswers: ["chickpeas", "chickpea", "garbanzo beans"] },
  { id: "en-foo-008", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "What do you call flat, round Middle Eastern bread often used for wraps?", acceptedAnswers: ["pita", "khubz", "flatbread"] },
  { id: "en-foo-009", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "What spice gives curry its distinctive yellow color?", acceptedAnswers: ["turmeric"] },
  { id: "en-foo-010", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "What drink is made by brewing roasted coffee beans?", acceptedAnswers: ["coffee"] },
  { id: "en-foo-011", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "What Middle Eastern dish consists of grilled, skewered meat?", acceptedAnswers: ["kebab", "shish kebab", "shawarma"] },
  { id: "en-foo-012", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "What Japanese noodle dish is served in a savory broth?", acceptedAnswers: ["ramen", "udon"] },
  { id: "en-foo-013", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "What Levantine dish is made of fried balls of ground chickpeas or fava beans?", acceptedAnswers: ["falafel"] },
  { id: "en-foo-014", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "What Italian dish is a thin, flattened, and often breaded cutlet?", acceptedAnswers: ["schnitzel", "cutlet", "milanese"] },
  { id: "en-foo-015", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "What Japanese dish is made of vinegared rice, usually with fish?", acceptedAnswers: ["sushi"] },
  { id: "en-foo-016", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "What Gulf-region rice dish is traditionally made with spiced meat, similar to biryani?", acceptedAnswers: ["kabsa", "machboos", "majboos"] },
  { id: "en-foo-017", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "What dessert is made of thin layers of pastry filled with nuts and honey syrup?", acceptedAnswers: ["baklava"] },
  { id: "en-foo-018", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "What condiment is made by fermenting cabbage in Korea?", acceptedAnswers: ["kimchi"] },
  { id: "en-foo-019", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "What sauce is traditionally made from tomatoes, used as a pasta base?", acceptedAnswers: ["marinara", "tomato sauce"] },
  { id: "en-foo-020", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "What Mexican dish consists of a tortilla folded around a filling?", acceptedAnswers: ["taco", "burrito", "quesadilla"] },
  { id: "en-foo-021", category: "FOOD_CULTURE", difficulty: "HARD", prompt: "What spice, derived from the crocus flower, is the most expensive in the world by weight?", acceptedAnswers: ["saffron"] },
  { id: "en-foo-022", category: "FOOD_CULTURE", difficulty: "HARD", prompt: "What fermented dairy drink is popular across South Asia and the Middle East?", acceptedAnswers: ["yogurt drink", "ayran", "lassi", "laban"] },
  { id: "en-foo-023", category: "FOOD_CULTURE", difficulty: "HARD", prompt: "What is the French culinary term for a cooking method that seals in flavor by browning meat quickly at high heat?", acceptedAnswers: ["searing", "sear"] },
  { id: "en-foo-024", category: "FOOD_CULTURE", difficulty: "HARD", prompt: "What Ottoman-origin sweet, soaked in syrup, is topped with a stringy, cheese-filled pastry?", acceptedAnswers: ["kunafa", "kanafeh"] },
  { id: "en-foo-025", category: "FOOD_CULTURE", difficulty: "HARD", prompt: "What grain, popular in Middle Eastern tabbouleh, is a form of cracked wheat?", acceptedAnswers: ["bulgur"] },
  { id: "en-foo-026", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "What is the main ingredient in traditional lemonade?", acceptedAnswers: ["lemon", "lemons"] },
  { id: "en-foo-027", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "What seed is used to make tahini?", acceptedAnswers: ["sesame", "sesame seeds"] },
  { id: "en-foo-028", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "What Indian bread is traditionally baked in a clay tandoor oven?", acceptedAnswers: ["naan", "tandoori bread"] },
  { id: "en-foo-029", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "What hot drink is traditionally served in small glasses across the Middle East, often with sugar?", acceptedAnswers: ["tea", "chai"] },
  { id: "en-foo-030", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "What Levantine salad is made of parsley, tomatoes, and bulgur wheat?", acceptedAnswers: ["tabbouleh"] },
];
