import type { TriviaContentItem } from "../types";

export const FUN_RANDOM: TriviaContentItem[] = [
  { id: "en-fun-001", category: "FUN_RANDOM", difficulty: "EASY", prompt: "How many legs does a spider have?", acceptedAnswers: ["8", "eight"] },
  { id: "en-fun-002", category: "FUN_RANDOM", difficulty: "EASY", prompt: "What is the fastest land animal?", acceptedAnswers: ["cheetah"] },
  { id: "en-fun-003", category: "FUN_RANDOM", difficulty: "EASY", prompt: "What do you call a baby cat?", acceptedAnswers: ["kitten"] },
  { id: "en-fun-004", category: "FUN_RANDOM", difficulty: "EASY", prompt: "What is the tallest animal in the world?", acceptedAnswers: ["giraffe"] },
  { id: "en-fun-005", category: "FUN_RANDOM", difficulty: "EASY", prompt: "What color is a polar bear's fur, despite looking white?", acceptedAnswers: ["clear", "transparent", "colorless"] },
  { id: "en-fun-006", category: "FUN_RANDOM", difficulty: "EASY", prompt: "What insect makes honey?", acceptedAnswers: ["bee", "bees"] },
  { id: "en-fun-007", category: "FUN_RANDOM", difficulty: "EASY", prompt: "How many hearts does an octopus have?", acceptedAnswers: ["3", "three"] },
  { id: "en-fun-008", category: "FUN_RANDOM", difficulty: "EASY", prompt: "What is a group of wolves called?", acceptedAnswers: ["pack"] },
  { id: "en-fun-009", category: "FUN_RANDOM", difficulty: "EASY", prompt: "What is the largest animal on Earth?", acceptedAnswers: ["blue whale"] },
  { id: "en-fun-010", category: "FUN_RANDOM", difficulty: "EASY", prompt: "What do chameleons famously do to blend into their surroundings?", acceptedAnswers: ["change color", "camouflage"] },
  { id: "en-fun-011", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "What is the only bird that can fly backwards?", acceptedAnswers: ["hummingbird"] },
  { id: "en-fun-012", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "How many hearts does an earthworm have?", acceptedAnswers: ["5", "five"] },
  { id: "en-fun-013", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "What is a baby kangaroo called?", acceptedAnswers: ["joey"] },
  { id: "en-fun-014", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "What is the only mammal that can't jump?", acceptedAnswers: ["elephant"] },
  { id: "en-fun-015", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "What is the world's largest coral reef system called?", acceptedAnswers: ["great barrier reef"] },
  { id: "en-fun-016", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "What color is a giraffe's tongue?", acceptedAnswers: ["black", "dark blue", "purple"] },
  { id: "en-fun-017", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "How many stomachs does a cow have?", acceptedAnswers: ["4", "four"] },
  { id: "en-fun-018", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "What is a group of flamingos called?", acceptedAnswers: ["flamboyance"] },
  { id: "en-fun-019", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "What everyday object was invented by Percy Spencer after a melted chocolate bar in his pocket?", acceptedAnswers: ["microwave", "microwave oven"] },
  { id: "en-fun-020", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "What fruit floats in water and is technically a berry, despite its name?", acceptedAnswers: ["banana", "watermelon", "avocado"] },
  { id: "en-fun-021", category: "FUN_RANDOM", difficulty: "HARD", prompt: "What is the only country in the world named after a woman?", acceptedAnswers: ["ireland"] },
  { id: "en-fun-022", category: "FUN_RANDOM", difficulty: "HARD", prompt: "What color is octopus blood?", acceptedAnswers: ["blue"] },
  { id: "en-fun-023", category: "FUN_RANDOM", difficulty: "HARD", prompt: "What is the shortest war in recorded history, lasting under an hour?", acceptedAnswers: ["anglo-zanzibar war"] },
  { id: "en-fun-024", category: "FUN_RANDOM", difficulty: "HARD", prompt: "What is the only letter that does not appear in any U.S. state name?", acceptedAnswers: ["q"] },
  { id: "en-fun-025", category: "FUN_RANDOM", difficulty: "HARD", prompt: "What is a group of crows called?", acceptedAnswers: ["murder"] },
  { id: "en-fun-026", category: "FUN_RANDOM", difficulty: "EASY", prompt: "How many colors are in a rainbow?", acceptedAnswers: ["7", "seven"] },
  { id: "en-fun-027", category: "FUN_RANDOM", difficulty: "EASY", prompt: "What do you call a shape with eight sides?", acceptedAnswers: ["octagon"] },
  { id: "en-fun-028", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "What everyday snack food was originally invented as a health food by a doctor?", acceptedAnswers: ["corn flakes", "cereal"] },
  { id: "en-fun-029", category: "FUN_RANDOM", difficulty: "EASY", prompt: "How many hours of sleep does an average adult need per night?", acceptedAnswers: ["7", "8", "7-9", "seven", "eight"] },
  { id: "en-fun-030", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "What is the only food that never spoils?", acceptedAnswers: ["honey"] },
];
