import type { TriviaContentItem } from "../types";

export const GENERAL_KNOWLEDGE: TriviaContentItem[] = [
  { id: "en-gen-001", category: "GENERAL", difficulty: "EASY", prompt: "How many days are there in a leap year?", acceptedAnswers: ["366"] },
  { id: "en-gen-002", category: "GENERAL", difficulty: "EASY", prompt: "What is the freezing point of water in Celsius?", acceptedAnswers: ["0", "zero"] },
  { id: "en-gen-003", category: "GENERAL", difficulty: "EASY", prompt: "How many continents are there on Earth?", acceptedAnswers: ["7", "seven"] },
  { id: "en-gen-004", category: "GENERAL", difficulty: "EASY", prompt: "What color do you get by mixing blue and yellow?", acceptedAnswers: ["green"] },
  { id: "en-gen-005", category: "GENERAL", difficulty: "EASY", prompt: "How many letters are in the English alphabet?", acceptedAnswers: ["26"] },
  { id: "en-gen-006", category: "GENERAL", difficulty: "EASY", prompt: "What is the largest organ in the human body?", acceptedAnswers: ["skin"] },
  { id: "en-gen-007", category: "GENERAL", difficulty: "EASY", prompt: "How many minutes are in a full day?", acceptedAnswers: ["1440"] },
  { id: "en-gen-008", category: "GENERAL", difficulty: "EASY", prompt: "What do bees produce that people eat?", acceptedAnswers: ["honey"] },
  { id: "en-gen-009", category: "GENERAL", difficulty: "EASY", prompt: "What is the opposite of 'hot'?", acceptedAnswers: ["cold"] },
  { id: "en-gen-010", category: "GENERAL", difficulty: "EASY", prompt: "How many sides does a hexagon have?", acceptedAnswers: ["6", "six"] },
  { id: "en-gen-011", category: "GENERAL", difficulty: "MEDIUM", prompt: "What is the smallest prime number?", acceptedAnswers: ["2", "two"] },
  { id: "en-gen-012", category: "GENERAL", difficulty: "MEDIUM", prompt: "What is the currency of Japan?", acceptedAnswers: ["yen"] },
  { id: "en-gen-013", category: "GENERAL", difficulty: "MEDIUM", prompt: "Name the gas plants absorb to perform photosynthesis.", acceptedAnswers: ["carbon dioxide", "co2"] },
  { id: "en-gen-014", category: "GENERAL", difficulty: "MEDIUM", prompt: "What is the unit used to measure electrical resistance?", acceptedAnswers: ["ohm", "ohms"] },
  { id: "en-gen-015", category: "GENERAL", difficulty: "MEDIUM", prompt: "What do you call a word that reads the same forwards and backwards?", acceptedAnswers: ["palindrome"] },
  { id: "en-gen-016", category: "GENERAL", difficulty: "MEDIUM", prompt: "How many bones are in the adult human body?", acceptedAnswers: ["206"] },
  { id: "en-gen-017", category: "GENERAL", difficulty: "MEDIUM", prompt: "What is the tallest animal in the world?", acceptedAnswers: ["giraffe"] },
  { id: "en-gen-018", category: "GENERAL", difficulty: "MEDIUM", prompt: "Name the largest planet in our solar system.", acceptedAnswers: ["jupiter"] },
  { id: "en-gen-019", category: "GENERAL", difficulty: "MEDIUM", prompt: "What is the study of weather called?", acceptedAnswers: ["meteorology"] },
  { id: "en-gen-020", category: "GENERAL", difficulty: "MEDIUM", prompt: "How many strings does a standard guitar have?", acceptedAnswers: ["6", "six"] },
  { id: "en-gen-021", category: "GENERAL", difficulty: "HARD", prompt: "What is the only mammal capable of true flight?", acceptedAnswers: ["bat"] },
  { id: "en-gen-022", category: "GENERAL", difficulty: "HARD", prompt: "What is the hardest natural substance on Earth?", acceptedAnswers: ["diamond"] },
  { id: "en-gen-023", category: "GENERAL", difficulty: "HARD", prompt: "Name the process by which a liquid turns directly into a gas without boiling.", acceptedAnswers: ["evaporation"] },
  { id: "en-gen-024", category: "GENERAL", difficulty: "HARD", prompt: "What is the SI unit of frequency?", acceptedAnswers: ["hertz", "hz"] },
  { id: "en-gen-025", category: "GENERAL", difficulty: "HARD", prompt: "Name the longest bone in the human body.", acceptedAnswers: ["femur", "thigh bone"] },
  { id: "en-gen-026", category: "GENERAL", difficulty: "EASY", prompt: "What do you call baby dogs?", acceptedAnswers: ["puppies", "puppy"] },
  { id: "en-gen-027", category: "GENERAL", difficulty: "EASY", prompt: "How many wheels does a standard bicycle have?", acceptedAnswers: ["2", "two"] },
  { id: "en-gen-028", category: "GENERAL", difficulty: "EASY", prompt: "What shape has three sides?", acceptedAnswers: ["triangle"] },
  { id: "en-gen-029", category: "GENERAL", difficulty: "EASY", prompt: "What is the first day of the week on most calendars?", acceptedAnswers: ["sunday", "monday"] },
  { id: "en-gen-030", category: "GENERAL", difficulty: "MEDIUM", prompt: "What do you call a group of lions?", acceptedAnswers: ["pride"] },
  { id: "en-gen-031", category: "GENERAL", difficulty: "MEDIUM", prompt: "What is the main language spoken in Brazil?", acceptedAnswers: ["portuguese"] },
  { id: "en-gen-032", category: "GENERAL", difficulty: "MEDIUM", prompt: "How many players are on a standard basketball team on the court at once?", acceptedAnswers: ["5", "five"] },
  { id: "en-gen-033", category: "GENERAL", difficulty: "HARD", prompt: "What is the powerhouse of the cell called?", acceptedAnswers: ["mitochondria", "mitochondrion"] },
  { id: "en-gen-034", category: "GENERAL", difficulty: "MEDIUM", prompt: "What device is used to measure atmospheric pressure?", acceptedAnswers: ["barometer"] },
  { id: "en-gen-035", category: "GENERAL", difficulty: "EASY", prompt: "What is the largest ocean on Earth?", acceptedAnswers: ["pacific", "pacific ocean"] },
  { id: "en-gen-036", category: "GENERAL", difficulty: "MEDIUM", prompt: "What natural phenomenon is measured using the Richter scale?", acceptedAnswers: ["earthquake", "earthquakes"] },
  { id: "en-gen-037", category: "GENERAL", difficulty: "EASY", prompt: "How many hours are there in a full week?", acceptedAnswers: ["168"] },
  { id: "en-gen-038", category: "GENERAL", difficulty: "HARD", prompt: "What metal is liquid at room temperature?", acceptedAnswers: ["mercury"] },
  { id: "en-gen-039", category: "GENERAL", difficulty: "MEDIUM", prompt: "What is the name for a shape with five sides?", acceptedAnswers: ["pentagon"] },
  { id: "en-gen-040", category: "GENERAL", difficulty: "EASY", prompt: "What do you call it when a plant makes its own food using sunlight?", acceptedAnswers: ["photosynthesis"] },
  { id: "en-gen-041", category: "GENERAL", difficulty: "MEDIUM", prompt: "Which country has the largest population in the world as of the 2020s?", acceptedAnswers: ["india"] },
  { id: "en-gen-042", category: "GENERAL", difficulty: "EASY", prompt: "What is the official language of Mexico?", acceptedAnswers: ["spanish"] },
  { id: "en-gen-043", category: "GENERAL", difficulty: "HARD", prompt: "What currency is shared by most countries in the European Union?", acceptedAnswers: ["euro"] },
];
