import type { TriviaContentItem } from "../types";

export const GEOGRAPHY: TriviaContentItem[] = [
  { id: "en-geo-001", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the largest ocean on Earth?", acceptedAnswers: ["pacific", "pacific ocean"] },
  { id: "en-geo-002", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the longest river in the world?", acceptedAnswers: ["nile"] },
  { id: "en-geo-003", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the largest desert in the world?", acceptedAnswers: ["sahara", "antarctic desert", "antarctica"] },
  { id: "en-geo-004", category: "GEOGRAPHY", difficulty: "EASY", prompt: "How many continents are there on Earth?", acceptedAnswers: ["7", "seven"] },
  { id: "en-geo-005", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the tallest mountain in the world?", acceptedAnswers: ["mount everest", "everest"] },
  { id: "en-geo-006", category: "GEOGRAPHY", difficulty: "EASY", prompt: "Which continent is the Sahara Desert located on?", acceptedAnswers: ["africa"] },
  { id: "en-geo-007", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the smallest continent by land area?", acceptedAnswers: ["australia", "oceania"] },
  { id: "en-geo-008", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What line of latitude divides the Earth into Northern and Southern Hemispheres?", acceptedAnswers: ["equator"] },
  { id: "en-geo-009", category: "GEOGRAPHY", difficulty: "EASY", prompt: "Which country is shaped like a boot?", acceptedAnswers: ["italy"] },
  { id: "en-geo-010", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "What mountain range separates Europe from Asia in Russia?", acceptedAnswers: ["ural mountains", "urals"] },
  { id: "en-geo-011", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "Which desert covers much of northern Africa?", acceptedAnswers: ["sahara"] },
  { id: "en-geo-012", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "What body of water separates the UK from mainland Europe?", acceptedAnswers: ["english channel", "the channel"] },
  { id: "en-geo-013", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "Which African country is completely surrounded by South Africa?", acceptedAnswers: ["lesotho"] },
  { id: "en-geo-014", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "What is the largest lake in the world by surface area?", acceptedAnswers: ["caspian sea"] },
  { id: "en-geo-015", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "Which strait separates Europe from Africa near Gibraltar?", acceptedAnswers: ["strait of gibraltar"] },
  { id: "en-geo-016", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "What is the driest continent (excluding Antarctica)?", acceptedAnswers: ["australia"] },
  { id: "en-geo-017", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "Which country has the most time zones?", acceptedAnswers: ["france"] },
  { id: "en-geo-018", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "What is the world's largest island?", acceptedAnswers: ["greenland"] },
  { id: "en-geo-019", category: "GEOGRAPHY", difficulty: "HARD", prompt: "What is the deepest point in the world's oceans called?", acceptedAnswers: ["mariana trench", "challenger deep"] },
  { id: "en-geo-020", category: "GEOGRAPHY", difficulty: "HARD", prompt: "Which country has the longest coastline in the world?", acceptedAnswers: ["canada"] },
  { id: "en-geo-021", category: "GEOGRAPHY", difficulty: "HARD", prompt: "What is the only sea without any coastline, bordered instead by ocean currents?", acceptedAnswers: ["sargasso sea"] },
  { id: "en-geo-022", category: "GEOGRAPHY", difficulty: "HARD", prompt: "Which African lake is the source of the White Nile?", acceptedAnswers: ["lake victoria"] },
  { id: "en-geo-023", category: "GEOGRAPHY", difficulty: "HARD", prompt: "What is the name of the imaginary line at 0 degrees longitude that passes through Greenwich?", acceptedAnswers: ["prime meridian"] },
  { id: "en-geo-024", category: "GEOGRAPHY", difficulty: "EASY", prompt: "Which ocean is located between Africa, Asia and Australia?", acceptedAnswers: ["indian ocean"] },
  { id: "en-geo-025", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "Which South American country is home to most of the Amazon Rainforest?", acceptedAnswers: ["brazil"] },
  { id: "en-geo-026", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "What is the highest waterfall in the world?", acceptedAnswers: ["angel falls"] },
  { id: "en-geo-027", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What continent is Egypt located on?", acceptedAnswers: ["africa"] },
  { id: "en-geo-028", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the capital of France?", acceptedAnswers: ["paris"] },
  { id: "en-geo-029", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the capital of the United States?", acceptedAnswers: ["washington", "washington dc", "washington d.c."] },
  { id: "en-geo-030", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the capital of Japan?", acceptedAnswers: ["tokyo"] },
  { id: "en-geo-031", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the capital of Italy?", acceptedAnswers: ["rome"] },
  { id: "en-geo-032", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the capital of the United Kingdom?", acceptedAnswers: ["london"] },
  { id: "en-geo-033", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the capital of Germany?", acceptedAnswers: ["berlin"] },
  { id: "en-geo-034", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the capital of Spain?", acceptedAnswers: ["madrid"] },
  { id: "en-geo-035", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the capital of Canada?", acceptedAnswers: ["ottawa"] },
  { id: "en-geo-036", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the capital of China?", acceptedAnswers: ["beijing"] },
  { id: "en-geo-037", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the capital of Russia?", acceptedAnswers: ["moscow"] },
  { id: "en-geo-038", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "What is the capital of Australia?", acceptedAnswers: ["canberra"] },
  { id: "en-geo-039", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "What is the capital of South Korea?", acceptedAnswers: ["seoul"] },
  { id: "en-geo-040", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "What is the capital of Brazil?", acceptedAnswers: ["brasilia"] },
  { id: "en-geo-041", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "What is the capital of Turkey?", acceptedAnswers: ["ankara"] },
  { id: "en-geo-042", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "What is the capital of Greece?", acceptedAnswers: ["athens"] },
  { id: "en-geo-043", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "Which country is home to the Eiffel Tower?", acceptedAnswers: ["france"] },
  { id: "en-geo-044", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "Which country is home to the Great Pyramid of Giza?", acceptedAnswers: ["egypt"] },
  { id: "en-geo-045", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "Which country is known as the Land of the Rising Sun?", acceptedAnswers: ["japan"] },
  { id: "en-geo-046", category: "GEOGRAPHY", difficulty: "HARD", prompt: "What is the capital of Kazakhstan?", acceptedAnswers: ["astana"] },
  { id: "en-geo-047", category: "GEOGRAPHY", difficulty: "HARD", prompt: "What is the smallest country in the world by area?", acceptedAnswers: ["vatican city", "vatican"] },
  { id: "en-geo-048", category: "GEOGRAPHY", difficulty: "HARD", prompt: "Which two countries share the longest international border in the world?", acceptedAnswers: ["canada and united states", "usa and canada", "canada and usa", "united states and canada"] },
  { id: "en-geo-049", category: "GEOGRAPHY", difficulty: "HARD", prompt: "What is the capital of Switzerland?", acceptedAnswers: ["bern"] },
  { id: "en-geo-050", category: "GEOGRAPHY", difficulty: "HARD", prompt: "Which country gifted the Statue of Liberty to the United States?", acceptedAnswers: ["france"] },
  { id: "en-geo-051", category: "GEOGRAPHY", difficulty: "EASY", prompt: "Which country is famous for the Eiffel Tower, the Louvre, and croissants?", acceptedAnswers: ["france"] },
  { id: "en-geo-052", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "Which country is shaped like a boot on the map of Europe?", acceptedAnswers: ["italy"] },
  { id: "en-geo-053", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "What is the largest country in the world by land area?", acceptedAnswers: ["russia"] },
  { id: "en-geo-054", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "What is the capital of India?", acceptedAnswers: ["new delhi", "delhi"] },
  { id: "en-geo-055", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "What is the capital of Portugal?", acceptedAnswers: ["lisbon"] },
  { id: "en-geo-056", category: "GEOGRAPHY", difficulty: "EASY", prompt: "In which country would you find the Statue of Liberty?", acceptedAnswers: ["united states", "usa", "us"] },
  { id: "en-geo-057", category: "GEOGRAPHY", difficulty: "HARD", prompt: "What is the capital of Norway?", acceptedAnswers: ["oslo"] },
  { id: "en-geo-058", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the capital and largest city of Egypt?", acceptedAnswers: ["cairo"] },
  { id: "en-geo-059", category: "GEOGRAPHY", difficulty: "EASY", prompt: "What is the capital of Saudi Arabia?", acceptedAnswers: ["riyadh"] },
  { id: "en-geo-060", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "What sea does Saudi Arabia, Egypt, and Jordan all border?", acceptedAnswers: ["red sea"] },
];
