import type { TriviaContentItem } from "../types";

export const HISTORY: TriviaContentItem[] = [
  { id: "en-his-001", category: "HISTORY", difficulty: "EASY", prompt: "In which century did World War II take place?", acceptedAnswers: ["20th", "twentieth"] },
  { id: "en-his-002", category: "HISTORY", difficulty: "EASY", prompt: "Who was the first President of the United States?", acceptedAnswers: ["george washington", "washington"] },
  { id: "en-his-003", category: "HISTORY", difficulty: "EASY", prompt: "Which ancient civilization built the pyramids of Giza?", acceptedAnswers: ["egyptians", "ancient egyptians", "egypt"] },
  { id: "en-his-004", category: "HISTORY", difficulty: "EASY", prompt: "In what year did World War II end?", acceptedAnswers: ["1945"] },
  { id: "en-his-005", category: "HISTORY", difficulty: "EASY", prompt: "Who is known for discovering America in 1492 in the traditional Western narrative?", acceptedAnswers: ["christopher columbus", "columbus"] },
  { id: "en-his-006", category: "HISTORY", difficulty: "EASY", prompt: "Which empire was ruled by Julius Caesar?", acceptedAnswers: ["roman empire", "rome"] },
  { id: "en-his-007", category: "HISTORY", difficulty: "EASY", prompt: "What wall divided East and West Berlin during the Cold War?", acceptedAnswers: ["berlin wall"] },
  { id: "en-his-008", category: "HISTORY", difficulty: "EASY", prompt: "Which ship famously sank in 1912 after hitting an iceberg?", acceptedAnswers: ["titanic"] },
  { id: "en-his-009", category: "HISTORY", difficulty: "EASY", prompt: "What ancient Egyptian structures were built as tombs for pharaohs?", acceptedAnswers: ["pyramids"] },
  { id: "en-his-010", category: "HISTORY", difficulty: "EASY", prompt: "Who was the British Prime Minister during most of World War II?", acceptedAnswers: ["winston churchill", "churchill"] },
  { id: "en-his-011", category: "HISTORY", difficulty: "MEDIUM", prompt: "In which year did the Berlin Wall fall?", acceptedAnswers: ["1989"] },
  { id: "en-his-012", category: "HISTORY", difficulty: "MEDIUM", prompt: "Who was the first Caliph of Islam after the Prophet Muhammad?", acceptedAnswers: ["abu bakr"] },
  { id: "en-his-013", category: "HISTORY", difficulty: "MEDIUM", prompt: "In which city was the ancient Library of Alexandria located?", acceptedAnswers: ["alexandria"] },
  { id: "en-his-014", category: "HISTORY", difficulty: "MEDIUM", prompt: "What was the name of the trade route connecting China to the Mediterranean?", acceptedAnswers: ["silk road"] },
  { id: "en-his-015", category: "HISTORY", difficulty: "MEDIUM", prompt: "Which explorer led the first expedition to circumnavigate the globe?", acceptedAnswers: ["magellan", "ferdinand magellan"] },
  { id: "en-his-016", category: "HISTORY", difficulty: "MEDIUM", prompt: "In what year did World War I begin?", acceptedAnswers: ["1914"] },
  { id: "en-his-017", category: "HISTORY", difficulty: "MEDIUM", prompt: "Who was the queen of Egypt famously allied with both Julius Caesar and Mark Antony?", acceptedAnswers: ["cleopatra"] },
  { id: "en-his-018", category: "HISTORY", difficulty: "MEDIUM", prompt: "What was the name of the ship that carried the Pilgrims to America in 1620?", acceptedAnswers: ["mayflower"] },
  { id: "en-his-019", category: "HISTORY", difficulty: "MEDIUM", prompt: "Which empire was ruled by Suleiman the Magnificent at its height?", acceptedAnswers: ["ottoman empire", "ottoman"] },
  { id: "en-his-020", category: "HISTORY", difficulty: "MEDIUM", prompt: "What French monument, built for a World's Fair, later became a global icon?", acceptedAnswers: ["eiffel tower"] },
  { id: "en-his-021", category: "HISTORY", difficulty: "HARD", prompt: "In what year did the French Revolution begin?", acceptedAnswers: ["1789"] },
  { id: "en-his-022", category: "HISTORY", difficulty: "HARD", prompt: "Who was the Mongol conqueror who founded the largest contiguous land empire in history?", acceptedAnswers: ["genghis khan"] },
  { id: "en-his-023", category: "HISTORY", difficulty: "HARD", prompt: "What treaty officially ended World War I?", acceptedAnswers: ["treaty of versailles", "versailles"] },
  { id: "en-his-024", category: "HISTORY", difficulty: "HARD", prompt: "Which ancient king is credited with one of the earliest known written law codes?", acceptedAnswers: ["hammurabi"] },
  { id: "en-his-025", category: "HISTORY", difficulty: "HARD", prompt: "In which century did the Renaissance begin in Europe?", acceptedAnswers: ["14th century", "14th", "fourteenth century"] },
  { id: "en-his-026", category: "HISTORY", difficulty: "EASY", prompt: "Which war was fought between the North and South regions of the United States?", acceptedAnswers: ["civil war", "american civil war"] },
  { id: "en-his-027", category: "HISTORY", difficulty: "EASY", prompt: "Who painted the Mona Lisa?", acceptedAnswers: ["leonardo da vinci", "da vinci"] },
  { id: "en-his-028", category: "HISTORY", difficulty: "MEDIUM", prompt: "Which ancient wonder of the world was a giant statue that stood at the entrance to a Greek harbor?", acceptedAnswers: ["colossus of rhodes", "colossus"] },
  { id: "en-his-029", category: "HISTORY", difficulty: "MEDIUM", prompt: "What was the name of the space race event where the US first landed on the Moon?", acceptedAnswers: ["apollo 11", "moon landing"] },
  { id: "en-his-030", category: "HISTORY", difficulty: "EASY", prompt: "In which decade did the internet become widely available to the public?", acceptedAnswers: ["1990s", "90s", "nineties"] },
];
