import type { ImpostorWordItem } from "../types";

// Secret words for the Impostor game. Everyone except the impostor sees the word and
// its category; the impostor only sees the category, then everyone gives a one-word
// clue in turn. Words are deliberately concrete and table-guessable within a
// restaurant/cafe setting.
export const IMPOSTOR_WORDS: ImpostorWordItem[] = [
  { id: "en-imp-001", category: "Food", word: "Pizza" },
  { id: "en-imp-002", category: "Food", word: "Sushi" },
  { id: "en-imp-003", category: "Food", word: "Burger" },
  { id: "en-imp-004", category: "Food", word: "Hummus" },
  { id: "en-imp-005", category: "Food", word: "Ice Cream" },
  { id: "en-imp-006", category: "Food", word: "Pasta" },
  { id: "en-imp-007", category: "Food", word: "Falafel" },
  { id: "en-imp-008", category: "Food", word: "Chocolate" },
  { id: "en-imp-009", category: "Animals", word: "Lion" },
  { id: "en-imp-010", category: "Animals", word: "Elephant" },
  { id: "en-imp-011", category: "Animals", word: "Penguin" },
  { id: "en-imp-012", category: "Animals", word: "Dolphin" },
  { id: "en-imp-013", category: "Animals", word: "Cat" },
  { id: "en-imp-014", category: "Animals", word: "Camel" },
  { id: "en-imp-015", category: "Animals", word: "Eagle" },
  { id: "en-imp-016", category: "Places", word: "Beach" },
  { id: "en-imp-017", category: "Places", word: "Airport" },
  { id: "en-imp-018", category: "Places", word: "Hospital" },
  { id: "en-imp-019", category: "Places", word: "Mosque" },
  { id: "en-imp-020", category: "Places", word: "Stadium" },
  { id: "en-imp-021", category: "Places", word: "Desert" },
  { id: "en-imp-022", category: "Places", word: "Library" },
  { id: "en-imp-023", category: "Movies & Shows", word: "Titanic" },
  { id: "en-imp-024", category: "Movies & Shows", word: "Spider-Man" },
  { id: "en-imp-025", category: "Movies & Shows", word: "Friends" },
  { id: "en-imp-026", category: "Movies & Shows", word: "The Lion King" },
  { id: "en-imp-027", category: "Movies & Shows", word: "Harry Potter" },
  { id: "en-imp-028", category: "Objects", word: "Umbrella" },
  { id: "en-imp-029", category: "Objects", word: "Mirror" },
  { id: "en-imp-030", category: "Objects", word: "Backpack" },
  { id: "en-imp-031", category: "Objects", word: "Clock" },
  { id: "en-imp-032", category: "Objects", word: "Candle" },
  { id: "en-imp-033", category: "Objects", word: "Phone" },
  { id: "en-imp-034", category: "Objects", word: "Sunglasses" },
  { id: "en-imp-035", category: "Sports", word: "Football" },
  { id: "en-imp-036", category: "Sports", word: "Basketball" },
  { id: "en-imp-037", category: "Sports", word: "Swimming" },
  { id: "en-imp-038", category: "Sports", word: "Tennis" },
  { id: "en-imp-039", category: "Sports", word: "Boxing" },
  { id: "en-imp-040", category: "Jobs", word: "Doctor" },
  { id: "en-imp-041", category: "Jobs", word: "Chef" },
  { id: "en-imp-042", category: "Jobs", word: "Pilot" },
  { id: "en-imp-043", category: "Jobs", word: "Teacher" },
  { id: "en-imp-044", category: "Jobs", word: "Waiter" },
  { id: "en-imp-045", category: "Jobs", word: "Firefighter" },
  { id: "en-imp-046", category: "Weather", word: "Thunderstorm" },
  { id: "en-imp-047", category: "Weather", word: "Snow" },
  { id: "en-imp-048", category: "Weather", word: "Rainbow" },
  { id: "en-imp-049", category: "Weather", word: "Heatwave" },
  { id: "en-imp-050", category: "Weather", word: "Fog" },
];
