import type { TriviaContentItem } from "../types";

export const SCIENCE: TriviaContentItem[] = [
  { id: "en-sci-001", category: "SCIENCE", difficulty: "EASY", prompt: "What planet is known as the Red Planet?", acceptedAnswers: ["mars"] },
  { id: "en-sci-002", category: "SCIENCE", difficulty: "EASY", prompt: "What gas do humans need to breathe to survive?", acceptedAnswers: ["oxygen"] },
  { id: "en-sci-003", category: "SCIENCE", difficulty: "EASY", prompt: "What is the chemical symbol for water?", acceptedAnswers: ["h2o"] },
  { id: "en-sci-004", category: "SCIENCE", difficulty: "EASY", prompt: "What organ pumps blood through the human body?", acceptedAnswers: ["heart"] },
  { id: "en-sci-005", category: "SCIENCE", difficulty: "EASY", prompt: "How many planets are in our solar system?", acceptedAnswers: ["8", "eight"] },
  { id: "en-sci-006", category: "SCIENCE", difficulty: "EASY", prompt: "What force pulls objects toward the Earth?", acceptedAnswers: ["gravity"] },
  { id: "en-sci-007", category: "SCIENCE", difficulty: "EASY", prompt: "What do you call an animal that eats only plants?", acceptedAnswers: ["herbivore"] },
  { id: "en-sci-008", category: "SCIENCE", difficulty: "EASY", prompt: "What star is at the center of our solar system?", acceptedAnswers: ["sun"] },
  { id: "en-sci-009", category: "SCIENCE", difficulty: "EASY", prompt: "What is the closest planet to the Sun?", acceptedAnswers: ["mercury"] },
  { id: "en-sci-010", category: "SCIENCE", difficulty: "EASY", prompt: "What part of the body do you use to see?", acceptedAnswers: ["eyes", "eye"] },
  { id: "en-sci-011", category: "SCIENCE", difficulty: "MEDIUM", prompt: "What is the chemical symbol for gold?", acceptedAnswers: ["au"] },
  { id: "en-sci-012", category: "SCIENCE", difficulty: "MEDIUM", prompt: "What is the process by which plants make their own food called?", acceptedAnswers: ["photosynthesis"] },
  { id: "en-sci-013", category: "SCIENCE", difficulty: "MEDIUM", prompt: "What is the largest planet in our solar system?", acceptedAnswers: ["jupiter"] },
  { id: "en-sci-014", category: "SCIENCE", difficulty: "MEDIUM", prompt: "What is the boiling point of water in Celsius?", acceptedAnswers: ["100"] },
  { id: "en-sci-015", category: "SCIENCE", difficulty: "MEDIUM", prompt: "Who developed the theory of evolution by natural selection?", acceptedAnswers: ["charles darwin", "darwin"] },
  { id: "en-sci-016", category: "SCIENCE", difficulty: "MEDIUM", prompt: "What is the powerhouse of the cell?", acceptedAnswers: ["mitochondria", "mitochondrion"] },
  { id: "en-sci-017", category: "SCIENCE", difficulty: "MEDIUM", prompt: "What type of energy is stored in a battery?", acceptedAnswers: ["chemical energy", "chemical"] },
  { id: "en-sci-018", category: "SCIENCE", difficulty: "MEDIUM", prompt: "What is the study of living organisms called?", acceptedAnswers: ["biology"] },
  { id: "en-sci-019", category: "SCIENCE", difficulty: "MEDIUM", prompt: "What gas do plants absorb from the atmosphere?", acceptedAnswers: ["carbon dioxide", "co2"] },
  { id: "en-sci-020", category: "SCIENCE", difficulty: "MEDIUM", prompt: "What is the freezing point of water in Fahrenheit?", acceptedAnswers: ["32"] },
  { id: "en-sci-021", category: "SCIENCE", difficulty: "HARD", prompt: "Who developed the theory of general relativity?", acceptedAnswers: ["albert einstein", "einstein"] },
  { id: "en-sci-022", category: "SCIENCE", difficulty: "HARD", prompt: "What is the chemical symbol for sodium?", acceptedAnswers: ["na"] },
  { id: "en-sci-023", category: "SCIENCE", difficulty: "HARD", prompt: "What particle has a negative electric charge in an atom?", acceptedAnswers: ["electron"] },
  { id: "en-sci-024", category: "SCIENCE", difficulty: "HARD", prompt: "What is the speed of light in a vacuum, approximately, in km per second?", acceptedAnswers: ["300000", "299792"] },
  { id: "en-sci-025", category: "SCIENCE", difficulty: "HARD", prompt: "What is the name of the galaxy that contains our solar system?", acceptedAnswers: ["milky way"] },
  { id: "en-sci-026", category: "SCIENCE", difficulty: "EASY", prompt: "What do you call a scientist who studies space?", acceptedAnswers: ["astronomer"] },
  { id: "en-sci-027", category: "SCIENCE", difficulty: "EASY", prompt: "What is H2O more commonly known as?", acceptedAnswers: ["water"] },
  { id: "en-sci-028", category: "SCIENCE", difficulty: "MEDIUM", prompt: "What is the hardest natural substance on Earth?", acceptedAnswers: ["diamond"] },
  { id: "en-sci-029", category: "SCIENCE", difficulty: "MEDIUM", prompt: "What vitamin does sunlight help your body produce?", acceptedAnswers: ["vitamin d"] },
  { id: "en-sci-030", category: "SCIENCE", difficulty: "HARD", prompt: "What is the only planet in our solar system that rotates on its side?", acceptedAnswers: ["uranus"] },
];
