import type { TriviaContentItem } from "../types";

export const SPORTS: TriviaContentItem[] = [
  { id: "en-spo-001", category: "SPORTS", difficulty: "EASY", prompt: "How many players are on a football (soccer) team on the field per side?", acceptedAnswers: ["11", "eleven"] },
  { id: "en-spo-002", category: "SPORTS", difficulty: "EASY", prompt: "Which country won the FIFA World Cup in 2022?", acceptedAnswers: ["argentina"] },
  { id: "en-spo-003", category: "SPORTS", difficulty: "EASY", prompt: "In tennis, what do you call a score of zero?", acceptedAnswers: ["love"] },
  { id: "en-spo-004", category: "SPORTS", difficulty: "EASY", prompt: "How many rings are on the Olympic flag?", acceptedAnswers: ["5", "five"] },
  { id: "en-spo-005", category: "SPORTS", difficulty: "EASY", prompt: "What sport is played at Wimbledon?", acceptedAnswers: ["tennis"] },
  { id: "en-spo-006", category: "SPORTS", difficulty: "EASY", prompt: "How many points is a touchdown worth in American football?", acceptedAnswers: ["6", "six"] },
  { id: "en-spo-007", category: "SPORTS", difficulty: "EASY", prompt: "Name a football club that plays in Spain's La Liga.", acceptedAnswers: ["real madrid", "barcelona", "atletico madrid", "sevilla", "valencia", "real sociedad", "athletic bilbao", "villarreal", "real betis"] },
  { id: "en-spo-008", category: "SPORTS", difficulty: "EASY", prompt: "How many players are on a basketball court per team during play?", acceptedAnswers: ["5", "five"] },
  { id: "en-spo-009", category: "SPORTS", difficulty: "EASY", prompt: "What shape is a boxing ring, despite its name?", acceptedAnswers: ["square"] },
  { id: "en-spo-010", category: "SPORTS", difficulty: "EASY", prompt: "What sport uses a shuttlecock?", acceptedAnswers: ["badminton"] },
  { id: "en-spo-011", category: "SPORTS", difficulty: "MEDIUM", prompt: "Which country has won the most FIFA World Cups?", acceptedAnswers: ["brazil"] },
  { id: "en-spo-012", category: "SPORTS", difficulty: "MEDIUM", prompt: "Name an NBA team based in California.", acceptedAnswers: ["lakers", "clippers", "warriors", "kings", "la lakers", "golden state warriors", "los angeles lakers", "los angeles clippers", "sacramento kings"] },
  { id: "en-spo-013", category: "SPORTS", difficulty: "MEDIUM", prompt: "How many holes are played in a standard round of golf?", acceptedAnswers: ["18", "eighteen"] },
  { id: "en-spo-014", category: "SPORTS", difficulty: "MEDIUM", prompt: "Name a Grand Slam tennis tournament.", acceptedAnswers: ["wimbledon", "us open", "french open", "australian open", "roland garros"] },
  { id: "en-spo-015", category: "SPORTS", difficulty: "MEDIUM", prompt: "In which sport would you perform a slam dunk?", acceptedAnswers: ["basketball"] },
  { id: "en-spo-016", category: "SPORTS", difficulty: "MEDIUM", prompt: "How many players are on the field for one team in cricket?", acceptedAnswers: ["11", "eleven"] },
  { id: "en-spo-017", category: "SPORTS", difficulty: "MEDIUM", prompt: "What is the maximum score in ten-pin bowling?", acceptedAnswers: ["300"] },
  { id: "en-spo-018", category: "SPORTS", difficulty: "MEDIUM", prompt: "Which sport is known as 'the sweet science'?", acceptedAnswers: ["boxing"] },
  { id: "en-spo-019", category: "SPORTS", difficulty: "MEDIUM", prompt: "Name a sport featured in the Summer Olympics.", acceptedAnswers: ["swimming", "athletics", "basketball", "football", "volleyball", "gymnastics", "boxing", "cycling", "tennis", "wrestling"] },
  { id: "en-spo-020", category: "SPORTS", difficulty: "MEDIUM", prompt: "How many players are on a volleyball team on the court per side?", acceptedAnswers: ["6", "six"] },
  { id: "en-spo-021", category: "SPORTS", difficulty: "HARD", prompt: "Who holds the record for most Formula 1 World Championships as of 2023?", acceptedAnswers: ["michael schumacher", "lewis hamilton", "schumacher", "hamilton"] },
  { id: "en-spo-022", category: "SPORTS", difficulty: "HARD", prompt: "In which country were the 2016 Summer Olympics held?", acceptedAnswers: ["brazil"] },
  { id: "en-spo-023", category: "SPORTS", difficulty: "HARD", prompt: "What is the term for a golf score of one under par?", acceptedAnswers: ["birdie"] },
  { id: "en-spo-024", category: "SPORTS", difficulty: "HARD", prompt: "Which country invented the sport of rugby?", acceptedAnswers: ["england"] },
  { id: "en-spo-025", category: "SPORTS", difficulty: "HARD", prompt: "How many players make up a rugby union team on the field?", acceptedAnswers: ["15", "fifteen"] },
  { id: "en-spo-026", category: "SPORTS", difficulty: "EASY", prompt: "What color card does a referee show for a serious foul in football?", acceptedAnswers: ["red"] },
  { id: "en-spo-027", category: "SPORTS", difficulty: "EASY", prompt: "In swimming, what stroke is swum on your back?", acceptedAnswers: ["backstroke"] },
  { id: "en-spo-028", category: "SPORTS", difficulty: "MEDIUM", prompt: "Which sport is played at the Tour de France?", acceptedAnswers: ["cycling"] },
  { id: "en-spo-029", category: "SPORTS", difficulty: "MEDIUM", prompt: "What piece of equipment protects a cricket batsman's legs?", acceptedAnswers: ["pads", "leg pads"] },
  { id: "en-spo-030", category: "SPORTS", difficulty: "HARD", prompt: "Which club has won the most UEFA Champions League titles?", acceptedAnswers: ["real madrid"] },
  { id: "en-spo-031", category: "SPORTS", difficulty: "EASY", prompt: "What do you call it when a football match ends 0-0?", acceptedAnswers: ["draw", "nil-nil", "scoreless draw", "tie"] },
  { id: "en-spo-032", category: "SPORTS", difficulty: "MEDIUM", prompt: "How many minutes are in a standard football (soccer) match, excluding stoppage time?", acceptedAnswers: ["90", "ninety"] },
  { id: "en-spo-033", category: "SPORTS", difficulty: "HARD", prompt: "Name the trophy awarded to the winner of the UEFA Champions League.", acceptedAnswers: ["champions league trophy", "the cup with the big ears", "european cup"] },
  { id: "en-spo-034", category: "SPORTS", difficulty: "EASY", prompt: "What is the national sport of Japan?", acceptedAnswers: ["sumo", "sumo wrestling"] },
  { id: "en-spo-035", category: "SPORTS", difficulty: "MEDIUM", prompt: "In athletics, what is the standard distance of a marathon in kilometers (rounded)?", acceptedAnswers: ["42", "42.2", "26.2 miles"] },
];
