import type { TriviaContentItem } from "../types";

export const ENTERTAINMENT: TriviaContentItem[] = [
  { id: "ar-ent-001", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "اذكر فيلماً من أفلام عالم مارفل السينمائي.", acceptedAnswers: ["المنتقمون", "الرجل الحديدي", "ثور", "الفهد الأسود", "الرجل العنكبوت", "كابتن أمريكا"] },
  { id: "ar-ent-002", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "من أخرج فيلم 'تايتانيك'؟", acceptedAnswers: ["جيمس كاميرون"] },
  { id: "ar-ent-003", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "ما اسم مدرسة السحر في سلسلة هاري بوتر؟", acceptedAnswers: ["هوغورتس", "هوجورتس"] },
  { id: "ar-ent-004", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "اذكر آلة موسيقية توجد عادة في الأوركسترا.", acceptedAnswers: ["الكمان", "التشيلو", "الفلوت", "البوق", "البيانو", "الكلارينيت", "الهارب", "الطبول"] },
  { id: "ar-ent-005", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "ما اللون الأساسي لبدلة الرجل العنكبوت؟", acceptedAnswers: ["الأحمر", "أحمر", "الأحمر والأزرق"] },
  { id: "ar-ent-006", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "من لعب دور 'جاك' في فيلم تايتانيك؟", acceptedAnswers: ["ليوناردو دي كابريو", "دي كابريو"] },
  { id: "ar-ent-007", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "ما لقب المغني مايكل جاكسون؟", acceptedAnswers: ["ملك البوب"] },
  { id: "ar-ent-008", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "اذكر إحدى أميرات ديزني.", acceptedAnswers: ["سندريلا", "بياض الثلج", "بيل", "أريل", "ياسمين", "موانا", "رابونزيل"] },
  { id: "ar-ent-009", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "أي شركة تنتج سلسلة أفلام 'توي ستوري'؟", acceptedAnswers: ["بيكسار", "ديزني"] },
  { id: "ar-ent-010", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "من هو بطل سلسلة أفلام 'جون ويك'؟", acceptedAnswers: ["كيانو ريفز"] },
  { id: "ar-ent-011", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "ما هو الفيلم الأعلى إيراداً في تاريخ السينما (غير معدّل للتضخم)؟", acceptedAnswers: ["أفاتار"] },
  { id: "ar-ent-012", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "من ألّف الموسيقى التصويرية لسلسلة 'حرب النجوم'؟", acceptedAnswers: ["جون ويليامز"] },
  { id: "ar-ent-013", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "من أخرج فيلمي 'إنسبشن' و'إنترستيلار'؟", acceptedAnswers: ["كريستوفر نولان"] },
  { id: "ar-ent-014", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "من مؤلفة سلسلة كتب هاري بوتر؟", acceptedAnswers: ["جي كي رولينغ", "رولينغ"] },
  { id: "ar-ent-015", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "ما اسم المملكة الأفريقية الخيالية في فيلم 'الفهد الأسود'؟", acceptedAnswers: ["واكاندا"] },
  { id: "ar-ent-016", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "أي استوديو أنتج فيلمي 'فروزن' و'موانا'؟", acceptedAnswers: ["ديزني"] },
  { id: "ar-ent-017", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "في أي مدينة تدور أحداث مسلسل 'فريندز'؟", acceptedAnswers: ["نيويورك"] },
  { id: "ar-ent-018", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "ما اسم المسلسل الذي يتبع عائلات ستارك ولانيستر وتارغاريان؟", acceptedAnswers: ["صراع العروش", "لعبة العروش"] },
  { id: "ar-ent-019", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "من هي الفنانة التي أصدرت ألبوم '1989'؟", acceptedAnswers: ["تايلور سويفت"] },
  { id: "ar-ent-020", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "أي بطل خارق يُعرف أيضاً بـ'فارس الظلام'؟", acceptedAnswers: ["باتمان"] },
  { id: "ar-ent-021", category: "ENTERTAINMENT", difficulty: "HARD", prompt: "من فاز بجائزة الأوسكار لأفضل ممثل عام 2020 عن فيلم 'جوكر'؟", acceptedAnswers: ["واكين فينيكس"] },
  { id: "ar-ent-022", category: "ENTERTAINMENT", difficulty: "HARD", prompt: "ما هو أول فيلم رسوم متحركة بالكمبيوتر بالكامل؟", acceptedAnswers: ["توي ستوري"] },
  { id: "ar-ent-023", category: "ENTERTAINMENT", difficulty: "HARD", prompt: "أي فيلم فاز بجائزة الأوسكار لأفضل فيلم عام 2020؟", acceptedAnswers: ["باراسايت", "طفيلي"] },
  { id: "ar-ent-024", category: "ENTERTAINMENT", difficulty: "HARD", prompt: "من أخرج الثلاثية الأصلية لسلسلة 'حرب النجوم'؟", acceptedAnswers: ["جورج لوكاس"] },
  { id: "ar-ent-025", category: "ENTERTAINMENT", difficulty: "HARD", prompt: "ما هو الاسم الحقيقي لمغني فرقة كوين الراحل؟", acceptedAnswers: ["فريدي ميركوري"] },
  { id: "ar-ent-026", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "ما نوع الحيوان الذي يمثله 'سيمبا' في فيلم 'الأسد الملك'؟", acceptedAnswers: ["أسد"] },
  { id: "ar-ent-027", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "ما اسم الشخصيات الصفراء في أفلام 'ديسبيكابل مي'؟", acceptedAnswers: ["مينيونز"] },
  { id: "ar-ent-028", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "ما اسم رياضة السحرة الخيالية التي تُلعب على المكانس في هاري بوتر؟", acceptedAnswers: ["كويدتش"] },
  { id: "ar-ent-029", category: "ENTERTAINMENT", difficulty: "MEDIUM", prompt: "ما اسم المقهى الشهير في مسلسل 'فريندز'؟", acceptedAnswers: ["سنترال بيرك"] },
  { id: "ar-ent-030", category: "ENTERTAINMENT", difficulty: "EASY", prompt: "أي منصة بث أنتجت مسلسل 'سترينجر ثينغز'؟", acceptedAnswers: ["نتفليكس"] },
];
