import type { TriviaContentItem } from "../types";

export const FOOD_CULTURE: TriviaContentItem[] = [
  { id: "ar-foo-001", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "اذكر طبقاً يحتوي على الأرز عادةً.", acceptedAnswers: ["برياني", "كبسة", "باييلا", "ريزوتو", "مجدرة"] },
  { id: "ar-foo-002", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "من أي دولة نشأت البيتزا تقليدياً؟", acceptedAnswers: ["إيطاليا", "ايطاليا"] },
  { id: "ar-foo-003", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "من أي دولة نشأ السوشي تقليدياً؟", acceptedAnswers: ["اليابان"] },
  { id: "ar-foo-004", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "ما هو المكوّن الرئيسي في الغواكامولي؟", acceptedAnswers: ["الأفوكادو"] },
  { id: "ar-foo-005", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "ما هي الحبوب المستخدمة لصنع الخبز؟", acceptedAnswers: ["القمح", "الطحين"] },
  { id: "ar-foo-006", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "أي فاكهة تُستخدم تقليدياً لصنع النبيذ؟", acceptedAnswers: ["العنب"] },
  { id: "ar-foo-007", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "ما هو المكوّن الرئيسي في الحمّص؟", acceptedAnswers: ["الحمّص", "الحمص"] },
  { id: "ar-foo-008", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "ما اسم الخبز المسطح الشائع في الشرق الأوسط؟", acceptedAnswers: ["خبز", "خبز عربي", "خبز صاج"] },
  { id: "ar-foo-009", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "أي توابل تعطي الكاري لونه الأصفر المميز؟", acceptedAnswers: ["الكركم"] },
  { id: "ar-foo-010", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "ما هو المشروب الذي يُصنع بتحميص وطحن حبوب البن؟", acceptedAnswers: ["القهوة"] },
  { id: "ar-foo-011", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "ما اسم الطبق الشرق أوسطي المكوّن من قطع لحم مشوية على أسياخ؟", acceptedAnswers: ["كباب", "شاورما", "شيش كباب"] },
  { id: "ar-foo-012", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "ما اسم الطبق اللبناني المصنوع من كرات مقلية من الحمّص أو الفول؟", acceptedAnswers: ["فلافل"] },
  { id: "ar-foo-013", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "ما اسم طبق الأرز الخليجي المصنوع باللحم المتبّل، شبيه بالبرياني؟", acceptedAnswers: ["كبسة", "مجبوس"] },
  { id: "ar-foo-014", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "ما اسم الحلوى المصنوعة من طبقات رقيقة من العجين محشوة بالمكسرات ومغطاة بالعسل؟", acceptedAnswers: ["بقلاوة"] },
  { id: "ar-foo-015", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "ما اسم الطبق الياباني المصنوع من الأرز المخلل عادةً مع السمك؟", acceptedAnswers: ["سوشي"] },
  { id: "ar-foo-016", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "ما اسم المخلل الكوري المصنوع من الملفوف المتخمر؟", acceptedAnswers: ["كيمتشي"] },
  { id: "ar-foo-017", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "ما اسم الصلصة الإيطالية المصنوعة أساساً من الطماطم وتُستخدم للمعكرونة؟", acceptedAnswers: ["صلصة الطماطم", "مارينارا"] },
  { id: "ar-foo-018", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "ما اسم الطبق المكسيكي المكوّن من خبز رقيق ملفوف حول حشوة؟", acceptedAnswers: ["تاكو", "بوريتو"] },
  { id: "ar-foo-019", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "ما اسم شوربة النودلز اليابانية التي تُقدّم في مرق لذيذ؟", acceptedAnswers: ["رامن"] },
  { id: "ar-foo-020", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "ما اسم الخبز الهندي الذي يُخبز تقليدياً في فرن طيني؟", acceptedAnswers: ["نان"] },
  { id: "ar-foo-021", category: "FOOD_CULTURE", difficulty: "HARD", prompt: "ما هي التوابل المستخرجة من زهرة الزعفران والتي تُعتبر الأغلى في العالم لوزنها؟", acceptedAnswers: ["الزعفران"] },
  { id: "ar-foo-022", category: "FOOD_CULTURE", difficulty: "HARD", prompt: "ما اسم مشروب اللبن المخمّر المنتشر في الشرق الأوسط وجنوب آسيا؟", acceptedAnswers: ["لبن", "عيران", "لاسي"] },
  { id: "ar-foo-023", category: "FOOD_CULTURE", difficulty: "HARD", prompt: "ما اسم الحلوى العثمانية المنقوعة بالشراب والمغطاة بعجين جبني متقطّع؟", acceptedAnswers: ["كنافة"] },
  { id: "ar-foo-024", category: "FOOD_CULTURE", difficulty: "HARD", prompt: "ما اسم الحبوب المستخدمة في التبولة، وهي شكل من أشكال القمح المجروش؟", acceptedAnswers: ["البرغل"] },
  { id: "ar-foo-025", category: "FOOD_CULTURE", difficulty: "HARD", prompt: "ما هو المصطلح الفرنسي لطريقة طهي تُحمّر فيها اللحوم بسرعة على حرارة عالية؟", acceptedAnswers: ["السير", "التحمير السريع"] },
  { id: "ar-foo-026", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "ما هو المكوّن الرئيسي في عصير الليمون التقليدي؟", acceptedAnswers: ["الليمون"] },
  { id: "ar-foo-027", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "أي بذور تُستخدم لصنع الطحينة؟", acceptedAnswers: ["السمسم"] },
  { id: "ar-foo-028", category: "FOOD_CULTURE", difficulty: "EASY", prompt: "ما اسم المشروب الساخن الذي يُقدّم في أكواب صغيرة مع السكر في الشرق الأوسط؟", acceptedAnswers: ["الشاي"] },
  { id: "ar-foo-029", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "ما اسم السلطة الشامية المصنوعة من البقدونس والطماطم والبرغل؟", acceptedAnswers: ["تبولة"] },
  { id: "ar-foo-030", category: "FOOD_CULTURE", difficulty: "MEDIUM", prompt: "ما اسم الطبق المصنوع من أوراق العنب المحشوة بالأرز؟", acceptedAnswers: ["ورق عنب", "دولمة"] },
];
