import type { TriviaContentItem } from "../types";

export const FUN_RANDOM: TriviaContentItem[] = [
  { id: "ar-fun-001", category: "FUN_RANDOM", difficulty: "EASY", prompt: "كم عدد أرجل العنكبوت؟", acceptedAnswers: ["8", "ثمانية"] },
  { id: "ar-fun-002", category: "FUN_RANDOM", difficulty: "EASY", prompt: "ما هو أسرع حيوان بري؟", acceptedAnswers: ["الفهد الصياد", "الفهد"] },
  { id: "ar-fun-003", category: "FUN_RANDOM", difficulty: "EASY", prompt: "ماذا نسمي صغير القطة؟", acceptedAnswers: ["هريرة", "قطيط"] },
  { id: "ar-fun-004", category: "FUN_RANDOM", difficulty: "EASY", prompt: "ما هو أطول حيوان في العالم؟", acceptedAnswers: ["الزرافة"] },
  { id: "ar-fun-005", category: "FUN_RANDOM", difficulty: "EASY", prompt: "أي حشرة تنتج العسل؟", acceptedAnswers: ["النحلة", "النحل"] },
  { id: "ar-fun-006", category: "FUN_RANDOM", difficulty: "EASY", prompt: "كم عدد قلوب الأخطبوط؟", acceptedAnswers: ["3", "ثلاثة"] },
  { id: "ar-fun-007", category: "FUN_RANDOM", difficulty: "EASY", prompt: "ماذا نسمي مجموعة من الذئاب؟", acceptedAnswers: ["قطيع", "سرب"] },
  { id: "ar-fun-008", category: "FUN_RANDOM", difficulty: "EASY", prompt: "ما هو أكبر حيوان على وجه الأرض؟", acceptedAnswers: ["الحوت الأزرق"] },
  { id: "ar-fun-009", category: "FUN_RANDOM", difficulty: "EASY", prompt: "ماذا يفعل الحرباء لتندمج مع محيطها؟", acceptedAnswers: ["تغيّر لونها", "تغيير اللون"] },
  { id: "ar-fun-010", category: "FUN_RANDOM", difficulty: "EASY", prompt: "كم عدد ألوان قوس قزح؟", acceptedAnswers: ["7", "سبعة"] },
  { id: "ar-fun-011", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "ما هو الطائر الوحيد القادر على الطيران للخلف؟", acceptedAnswers: ["الطائر الطنان"] },
  { id: "ar-fun-012", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "ماذا نسمي صغير الكنغر؟", acceptedAnswers: ["جوي"] },
  { id: "ar-fun-013", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "ما هو الثديي الوحيد الذي لا يستطيع القفز؟", acceptedAnswers: ["الفيل"] },
  { id: "ar-fun-014", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "ما اسم أكبر نظام شعاب مرجانية في العالم؟", acceptedAnswers: ["الحاجز المرجاني العظيم"] },
  { id: "ar-fun-015", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "كم عدد معدات الأبقار؟", acceptedAnswers: ["4", "أربعة"] },
  { id: "ar-fun-016", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "ماذا نسمي مجموعة من طيور الفلامنغو؟", acceptedAnswers: ["سرب"] },
  { id: "ar-fun-017", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "أي فاكهة تطفو على سطح الماء رغم كونها من التوت علمياً؟", acceptedAnswers: ["الموز", "البطيخ", "الأفوكادو"] },
  { id: "ar-fun-018", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "ما هو الطعام الوحيد الذي لا يفسد أبداً؟", acceptedAnswers: ["العسل"] },
  { id: "ar-fun-019", category: "FUN_RANDOM", difficulty: "HARD", prompt: "ما لون دم الأخطبوط؟", acceptedAnswers: ["أزرق"] },
  { id: "ar-fun-020", category: "FUN_RANDOM", difficulty: "HARD", prompt: "ما هي الدولة الوحيدة في العالم المسمّاة باسم امرأة؟", acceptedAnswers: ["أيرلندا", "ايرلندا"] },
  { id: "ar-fun-021", category: "FUN_RANDOM", difficulty: "HARD", prompt: "ماذا نسمي مجموعة من الغربان؟", acceptedAnswers: ["سرب"] },
  { id: "ar-fun-022", category: "FUN_RANDOM", difficulty: "EASY", prompt: "ماذا نسمي شكلاً له ثمانية أضلاع؟", acceptedAnswers: ["مثمن"] },
  { id: "ar-fun-023", category: "FUN_RANDOM", difficulty: "EASY", prompt: "كم عدد ساعات النوم التي يحتاجها البالغ عادةً في الليلة؟", acceptedAnswers: ["7", "8", "سبع", "ثماني"] },
  { id: "ar-fun-024", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "كم عدد معدات الإبل؟", acceptedAnswers: ["3", "ثلاثة"] },
  { id: "ar-fun-025", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "ما هو الحيوان الذي يمتلك أقوى عضة بين الثدييات؟", acceptedAnswers: ["فرس النهر", "التمساح"] },
  { id: "ar-fun-026", category: "FUN_RANDOM", difficulty: "EASY", prompt: "كم عدد أرجل النملة؟", acceptedAnswers: ["6", "ستة"] },
  { id: "ar-fun-027", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "ما اسم أصغر طائر في العالم؟", acceptedAnswers: ["الطنان النحلي", "الطائر الطنان"] },
  { id: "ar-fun-028", category: "FUN_RANDOM", difficulty: "HARD", prompt: "ما هو الحيوان الوحيد الذي لا يستطيع أن يخرج لسانه؟", acceptedAnswers: ["التمساح"] },
  { id: "ar-fun-029", category: "FUN_RANDOM", difficulty: "MEDIUM", prompt: "ما هو أثقل حيوان بري في العالم؟", acceptedAnswers: ["الفيل الأفريقي", "الفيل"] },
  { id: "ar-fun-030", category: "FUN_RANDOM", difficulty: "EASY", prompt: "أي حيوان يُعرف بأنه أفضل صديق للإنسان؟", acceptedAnswers: ["الكلب"] },
];
