import type { TriviaContentItem } from "../types";

export const GENERAL_KNOWLEDGE: TriviaContentItem[] = [
  { id: "ar-gen-001", category: "GENERAL", difficulty: "EASY", prompt: "كم عدد أيام السنة الكبيسة؟", acceptedAnswers: ["366"] },
  { id: "ar-gen-002", category: "GENERAL", difficulty: "EASY", prompt: "ما هي درجة تجمد الماء بالمئوية؟", acceptedAnswers: ["0", "صفر"] },
  { id: "ar-gen-003", category: "GENERAL", difficulty: "EASY", prompt: "كم عدد قارات الأرض؟", acceptedAnswers: ["7", "سبع", "سبعة"] },
  { id: "ar-gen-004", category: "GENERAL", difficulty: "EASY", prompt: "ما اللون الناتج عن مزج الأزرق والأصفر؟", acceptedAnswers: ["أخضر", "اخضر"] },
  { id: "ar-gen-005", category: "GENERAL", difficulty: "EASY", prompt: "كم عدد حروف الأبجدية الإنجليزية؟", acceptedAnswers: ["26"] },
  { id: "ar-gen-006", category: "GENERAL", difficulty: "EASY", prompt: "ما هو أكبر عضو في جسم الإنسان؟", acceptedAnswers: ["الجلد"] },
  { id: "ar-gen-007", category: "GENERAL", difficulty: "EASY", prompt: "كم عدد دقائق اليوم الكامل؟", acceptedAnswers: ["1440"] },
  { id: "ar-gen-008", category: "GENERAL", difficulty: "EASY", prompt: "ماذا ينتج النحل ويأكله الناس؟", acceptedAnswers: ["العسل", "عسل"] },
  { id: "ar-gen-009", category: "GENERAL", difficulty: "EASY", prompt: "ما عكس كلمة 'ساخن'؟", acceptedAnswers: ["بارد"] },
  { id: "ar-gen-010", category: "GENERAL", difficulty: "EASY", prompt: "كم عدد أضلاع الشكل السداسي؟", acceptedAnswers: ["6", "ستة"] },
  { id: "ar-gen-011", category: "GENERAL", difficulty: "MEDIUM", prompt: "ما هو أصغر عدد أولي؟", acceptedAnswers: ["2", "اثنان"] },
  { id: "ar-gen-012", category: "GENERAL", difficulty: "MEDIUM", prompt: "ما هي عملة اليابان؟", acceptedAnswers: ["الين", "ين"] },
  { id: "ar-gen-013", category: "GENERAL", difficulty: "MEDIUM", prompt: "ما اسم الغاز الذي تمتصه النباتات لعملية التمثيل الضوئي؟", acceptedAnswers: ["ثاني أكسيد الكربون", "ثاني اكسيد الكربون"] },
  { id: "ar-gen-014", category: "GENERAL", difficulty: "MEDIUM", prompt: "ما هي الوحدة المستخدمة لقياس المقاومة الكهربائية؟", acceptedAnswers: ["أوم", "اوم"] },
  { id: "ar-gen-015", category: "GENERAL", difficulty: "MEDIUM", prompt: "كم عدد عظام جسم الإنسان البالغ؟", acceptedAnswers: ["206"] },
  { id: "ar-gen-016", category: "GENERAL", difficulty: "MEDIUM", prompt: "ما هو أطول حيوان في العالم؟", acceptedAnswers: ["الزرافة", "زرافة"] },
  { id: "ar-gen-017", category: "GENERAL", difficulty: "MEDIUM", prompt: "ما هو أكبر كوكب في مجموعتنا الشمسية؟", acceptedAnswers: ["المشتري", "مشتري"] },
  { id: "ar-gen-018", category: "GENERAL", difficulty: "MEDIUM", prompt: "ما اسم علم دراسة الطقس؟", acceptedAnswers: ["الأرصاد الجوية", "علم الأرصاد"] },
  { id: "ar-gen-019", category: "GENERAL", difficulty: "MEDIUM", prompt: "كم عدد أوتار الغيتار العادي؟", acceptedAnswers: ["6", "ستة"] },
  { id: "ar-gen-020", category: "GENERAL", difficulty: "MEDIUM", prompt: "ما هو أصغر رقم فردي موجب؟", acceptedAnswers: ["1", "واحد"] },
  { id: "ar-gen-021", category: "GENERAL", difficulty: "HARD", prompt: "ما هو الثدي الوحيد القادر على الطيران الحقيقي؟", acceptedAnswers: ["الخفاش", "خفاش"] },
  { id: "ar-gen-022", category: "GENERAL", difficulty: "HARD", prompt: "ما هي أصلب مادة طبيعية على وجه الأرض؟", acceptedAnswers: ["الماس", "الألماس"] },
  { id: "ar-gen-023", category: "GENERAL", difficulty: "HARD", prompt: "ما اسم العملية التي يتحول فيها السائل إلى غاز دون غليان؟", acceptedAnswers: ["التبخر", "تبخر"] },
  { id: "ar-gen-024", category: "GENERAL", difficulty: "HARD", prompt: "ما هي وحدة قياس التردد في النظام الدولي؟", acceptedAnswers: ["هرتز"] },
  { id: "ar-gen-025", category: "GENERAL", difficulty: "HARD", prompt: "ما هو أطول عظم في جسم الإنسان؟", acceptedAnswers: ["عظمة الفخذ", "الفخذ"] },
  { id: "ar-gen-026", category: "GENERAL", difficulty: "EASY", prompt: "ماذا نسمي صغار الكلاب؟", acceptedAnswers: ["جراء", "جرو"] },
  { id: "ar-gen-027", category: "GENERAL", difficulty: "EASY", prompt: "كم عدد عجلات الدراجة الهوائية العادية؟", acceptedAnswers: ["2", "اثنان", "اثنتان"] },
  { id: "ar-gen-028", category: "GENERAL", difficulty: "EASY", prompt: "ما اسم الشكل الذي له ثلاثة أضلاع؟", acceptedAnswers: ["مثلث"] },
  { id: "ar-gen-029", category: "GENERAL", difficulty: "MEDIUM", prompt: "ماذا نسمي مجموعة من الأسود؟", acceptedAnswers: ["قطيع", "زمرة"] },
  { id: "ar-gen-030", category: "GENERAL", difficulty: "MEDIUM", prompt: "كم عدد لاعبي فريق كرة السلة على أرض الملعب في نفس الوقت؟", acceptedAnswers: ["5", "خمسة"] },
  { id: "ar-gen-031", category: "GENERAL", difficulty: "HARD", prompt: "ما هو اسم مركز إنتاج الطاقة داخل الخلية؟", acceptedAnswers: ["الميتوكندريا", "الميتوكوندريا"] },
  { id: "ar-gen-032", category: "GENERAL", difficulty: "MEDIUM", prompt: "ما اسم الجهاز المستخدم لقياس الضغط الجوي؟", acceptedAnswers: ["البارومتر"] },
  { id: "ar-gen-033", category: "GENERAL", difficulty: "EASY", prompt: "ما هو أكبر محيط في العالم؟", acceptedAnswers: ["المحيط الهادئ", "الهادئ"] },
  { id: "ar-gen-034", category: "GENERAL", difficulty: "MEDIUM", prompt: "ما هي الظاهرة الطبيعية التي تُقاس بمقياس ريختر؟", acceptedAnswers: ["الزلازل", "الزلزال"] },
  { id: "ar-gen-035", category: "GENERAL", difficulty: "EASY", prompt: "كم عدد ساعات الأسبوع الكامل؟", acceptedAnswers: ["168"] },
  { id: "ar-gen-036", category: "GENERAL", difficulty: "HARD", prompt: "ما هو المعدن السائل في درجة حرارة الغرفة؟", acceptedAnswers: ["الزئبق"] },
  { id: "ar-gen-037", category: "GENERAL", difficulty: "MEDIUM", prompt: "ما اسم الشكل الذي له خمسة أضلاع؟", acceptedAnswers: ["خماسي", "مخمس"] },
  { id: "ar-gen-038", category: "GENERAL", difficulty: "EASY", prompt: "ما اسم العملية التي تصنع بها النباتات غذاءها من ضوء الشمس؟", acceptedAnswers: ["التمثيل الضوئي", "البناء الضوئي"] },
  { id: "ar-gen-039", category: "GENERAL", difficulty: "MEDIUM", prompt: "ما هي أكثر دولة سكاناً في العالم في العقد الحالي؟", acceptedAnswers: ["الهند"] },
  { id: "ar-gen-040", category: "GENERAL", difficulty: "HARD", prompt: "ما هي العملة المشتركة لمعظم دول الاتحاد الأوروبي؟", acceptedAnswers: ["اليورو", "يورو"] },
];
