import type { TriviaContentItem } from "../types";

export const GEOGRAPHY: TriviaContentItem[] = [
  { id: "ar-geo-001", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هو أكبر محيط في العالم؟", acceptedAnswers: ["المحيط الهادئ", "الهادئ"] },
  { id: "ar-geo-002", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هو أطول نهر في العالم؟", acceptedAnswers: ["نهر النيل", "النيل"] },
  { id: "ar-geo-003", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هي أكبر صحراء في العالم؟", acceptedAnswers: ["الصحراء الكبرى", "صحراء القارة القطبية"] },
  { id: "ar-geo-004", category: "GEOGRAPHY", difficulty: "EASY", prompt: "كم عدد قارات العالم؟", acceptedAnswers: ["7", "سبع", "سبعة"] },
  { id: "ar-geo-005", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هو أعلى جبل في العالم؟", acceptedAnswers: ["إفرست", "جبل إفرست"] },
  { id: "ar-geo-006", category: "GEOGRAPHY", difficulty: "EASY", prompt: "في أي قارة تقع الصحراء الكبرى؟", acceptedAnswers: ["أفريقيا", "افريقيا"] },
  { id: "ar-geo-007", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هي أصغر قارة من حيث المساحة؟", acceptedAnswers: ["أستراليا", "استراليا", "أوقيانوسيا"] },
  { id: "ar-geo-008", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما اسم خط العرض الذي يقسم الأرض إلى نصفين شمالي وجنوبي؟", acceptedAnswers: ["خط الاستواء"] },
  { id: "ar-geo-009", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هي الدولة التي تشبه خريطتها شكل الحذاء؟", acceptedAnswers: ["إيطاليا", "ايطاليا"] },
  { id: "ar-geo-010", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "ما هي أصغر دولة في العالم من حيث المساحة؟", acceptedAnswers: ["الفاتيكان"] },
  { id: "ar-geo-011", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "أي سلسلة جبال تفصل بين قارتي أوروبا وآسيا في روسيا؟", acceptedAnswers: ["جبال الأورال"] },
  { id: "ar-geo-012", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "ما اسم المسطح المائي الذي يفصل بين بريطانيا وأوروبا القارية؟", acceptedAnswers: ["القناة الإنجليزية", "المانش"] },
  { id: "ar-geo-013", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "ما هي أكبر بحيرة في العالم من حيث المساحة؟", acceptedAnswers: ["بحر قزوين"] },
  { id: "ar-geo-014", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "ما اسم المضيق الذي يفصل أوروبا عن أفريقيا بالقرب من جبل طارق؟", acceptedAnswers: ["مضيق جبل طارق"] },
  { id: "ar-geo-015", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "ما هي أكثر القارات جفافاً باستثناء القارة القطبية الجنوبية؟", acceptedAnswers: ["أستراليا", "استراليا"] },
  { id: "ar-geo-016", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "ما هي أكبر جزيرة في العالم؟", acceptedAnswers: ["غرينلاند"] },
  { id: "ar-geo-017", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "ما هي أكبر دولة في العالم من حيث المساحة؟", acceptedAnswers: ["روسيا"] },
  { id: "ar-geo-018", category: "GEOGRAPHY", difficulty: "HARD", prompt: "ما اسم أعمق نقطة في محيطات العالم؟", acceptedAnswers: ["خندق ماريانا", "أعماق تشالنجر"] },
  { id: "ar-geo-019", category: "GEOGRAPHY", difficulty: "HARD", prompt: "أي دولة تمتلك أطول خط ساحلي في العالم؟", acceptedAnswers: ["كندا"] },
  { id: "ar-geo-020", category: "GEOGRAPHY", difficulty: "HARD", prompt: "ما اسم الخط الوهمي عند خط الطول صفر الذي يمر بغرينتش؟", acceptedAnswers: ["خط غرينتش", "خط الطول الأساسي"] },
  { id: "ar-geo-021", category: "GEOGRAPHY", difficulty: "EASY", prompt: "أي محيط يقع بين أفريقيا وآسيا وأستراليا؟", acceptedAnswers: ["المحيط الهندي"] },
  { id: "ar-geo-022", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "أي دولة في أمريكا الجنوبية تضم الجزء الأكبر من غابات الأمازون؟", acceptedAnswers: ["البرازيل"] },
  { id: "ar-geo-023", category: "GEOGRAPHY", difficulty: "HARD", prompt: "ما هو أعلى شلال في العالم؟", acceptedAnswers: ["شلالات أنجل"] },
  { id: "ar-geo-024", category: "GEOGRAPHY", difficulty: "EASY", prompt: "في أي قارة تقع مصر؟", acceptedAnswers: ["أفريقيا", "افريقيا"] },
  { id: "ar-geo-025", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هي عاصمة فرنسا؟", acceptedAnswers: ["باريس"] },
  { id: "ar-geo-026", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هي عاصمة اليابان؟", acceptedAnswers: ["طوكيو"] },
  { id: "ar-geo-027", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هي عاصمة إيطاليا؟", acceptedAnswers: ["روما"] },
  { id: "ar-geo-028", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هي عاصمة المملكة المتحدة؟", acceptedAnswers: ["لندن"] },
  { id: "ar-geo-029", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هي عاصمة ألمانيا؟", acceptedAnswers: ["برلين"] },
  { id: "ar-geo-030", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هي عاصمة إسبانيا؟", acceptedAnswers: ["مدريد"] },
  { id: "ar-geo-031", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هي عاصمة كندا؟", acceptedAnswers: ["أوتاوا"] },
  { id: "ar-geo-032", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هي عاصمة الصين؟", acceptedAnswers: ["بكين"] },
  { id: "ar-geo-033", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هي عاصمة روسيا؟", acceptedAnswers: ["موسكو"] },
  { id: "ar-geo-034", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "ما هي عاصمة أستراليا؟", acceptedAnswers: ["كانبرا"] },
  { id: "ar-geo-035", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "ما هي عاصمة كوريا الجنوبية؟", acceptedAnswers: ["سيول"] },
  { id: "ar-geo-036", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "ما هي عاصمة البرازيل؟", acceptedAnswers: ["برازيليا"] },
  { id: "ar-geo-037", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "ما هي عاصمة تركيا؟", acceptedAnswers: ["أنقرة", "انقرة"] },
  { id: "ar-geo-038", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "ما هي عاصمة اليونان؟", acceptedAnswers: ["أثينا", "اثينا"] },
  { id: "ar-geo-039", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "أي دولة تقع فيها برج إيفل؟", acceptedAnswers: ["فرنسا"] },
  { id: "ar-geo-040", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "أي دولة تقع فيها أهرامات الجيزة؟", acceptedAnswers: ["مصر"] },
  { id: "ar-geo-041", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "ما هي الدولة المعروفة بـ'أرض الشمس المشرقة'؟", acceptedAnswers: ["اليابان"] },
  { id: "ar-geo-042", category: "GEOGRAPHY", difficulty: "HARD", prompt: "ما هي عاصمة كازاخستان؟", acceptedAnswers: ["أستانا", "استانا"] },
  { id: "ar-geo-043", category: "GEOGRAPHY", difficulty: "HARD", prompt: "أي دولتين تتشاركان أطول حدود دولية في العالم؟", acceptedAnswers: ["كندا والولايات المتحدة", "الولايات المتحدة وكندا"] },
  { id: "ar-geo-044", category: "GEOGRAPHY", difficulty: "HARD", prompt: "ما هي عاصمة سويسرا؟", acceptedAnswers: ["برن"] },
  { id: "ar-geo-045", category: "GEOGRAPHY", difficulty: "HARD", prompt: "أي دولة أهدت تمثال الحرية إلى الولايات المتحدة؟", acceptedAnswers: ["فرنسا"] },
  { id: "ar-geo-046", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "ما هي عاصمة الهند؟", acceptedAnswers: ["نيودلهي", "دلهي"] },
  { id: "ar-geo-047", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "ما هي عاصمة البرتغال؟", acceptedAnswers: ["لشبونة"] },
  { id: "ar-geo-048", category: "GEOGRAPHY", difficulty: "EASY", prompt: "في أي دولة يقع تمثال الحرية؟", acceptedAnswers: ["الولايات المتحدة", "أمريكا"] },
  { id: "ar-geo-049", category: "GEOGRAPHY", difficulty: "HARD", prompt: "ما هي عاصمة النرويج؟", acceptedAnswers: ["أوسلو"] },
  { id: "ar-geo-050", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هي عاصمة مصر؟", acceptedAnswers: ["القاهرة"] },
  { id: "ar-geo-051", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هي عاصمة المملكة العربية السعودية؟", acceptedAnswers: ["الرياض"] },
  { id: "ar-geo-052", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "أي بحر تطل عليه كل من السعودية ومصر والأردن؟", acceptedAnswers: ["البحر الأحمر"] },
  { id: "ar-geo-053", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هي عاصمة الإمارات العربية المتحدة؟", acceptedAnswers: ["أبوظبي", "ابوظبي"] },
  { id: "ar-geo-054", category: "GEOGRAPHY", difficulty: "EASY", prompt: "ما هي عاصمة الأردن؟", acceptedAnswers: ["عمان"] },
  { id: "ar-geo-055", category: "GEOGRAPHY", difficulty: "MEDIUM", prompt: "ما هي عاصمة المغرب؟", acceptedAnswers: ["الرباط"] },
];
