import type { TriviaContentItem } from "../types";

export const HISTORY: TriviaContentItem[] = [
  { id: "ar-his-001", category: "HISTORY", difficulty: "EASY", prompt: "في أي قرن وقعت الحرب العالمية الثانية؟", acceptedAnswers: ["العشرين", "القرن العشرين"] },
  { id: "ar-his-002", category: "HISTORY", difficulty: "EASY", prompt: "من هو أول رئيس للولايات المتحدة الأمريكية؟", acceptedAnswers: ["جورج واشنطن", "واشنطن"] },
  { id: "ar-his-003", category: "HISTORY", difficulty: "EASY", prompt: "أي حضارة قديمة بنت أهرامات الجيزة؟", acceptedAnswers: ["المصريون القدماء", "الفراعنة", "مصر القديمة"] },
  { id: "ar-his-004", category: "HISTORY", difficulty: "EASY", prompt: "في أي عام انتهت الحرب العالمية الثانية؟", acceptedAnswers: ["1945"] },
  { id: "ar-his-005", category: "HISTORY", difficulty: "EASY", prompt: "ما هي السفينة الشهيرة التي غرقت عام 1912 بعد اصطدامها بجبل جليدي؟", acceptedAnswers: ["تايتانيك"] },
  { id: "ar-his-006", category: "HISTORY", difficulty: "EASY", prompt: "ما اسم الإمبراطورية التي حكمها يوليوس قيصر؟", acceptedAnswers: ["الإمبراطورية الرومانية", "روما"] },
  { id: "ar-his-007", category: "HISTORY", difficulty: "EASY", prompt: "ما اسم الجدار الذي فصل بين شرق وغرب برلين خلال الحرب الباردة؟", acceptedAnswers: ["جدار برلين"] },
  { id: "ar-his-008", category: "HISTORY", difficulty: "EASY", prompt: "ما اسم الهياكل المصرية القديمة التي بُنيت كمقابر للفراعنة؟", acceptedAnswers: ["الأهرامات"] },
  { id: "ar-his-009", category: "HISTORY", difficulty: "EASY", prompt: "من كان رئيس وزراء بريطانيا خلال معظم فترة الحرب العالمية الثانية؟", acceptedAnswers: ["ونستون تشرشل", "تشرشل"] },
  { id: "ar-his-010", category: "HISTORY", difficulty: "EASY", prompt: "من رسم لوحة 'الموناليزا'؟", acceptedAnswers: ["ليوناردو دافنشي", "دافنشي"] },
  { id: "ar-his-011", category: "HISTORY", difficulty: "MEDIUM", prompt: "في أي عام سقط جدار برلين؟", acceptedAnswers: ["1989"] },
  { id: "ar-his-012", category: "HISTORY", difficulty: "MEDIUM", prompt: "من هو أول خليفة للمسلمين بعد وفاة النبي محمد؟", acceptedAnswers: ["أبو بكر الصديق", "أبو بكر"] },
  { id: "ar-his-013", category: "HISTORY", difficulty: "MEDIUM", prompt: "في أي مدينة كانت تقع مكتبة الإسكندرية القديمة؟", acceptedAnswers: ["الإسكندرية"] },
  { id: "ar-his-014", category: "HISTORY", difficulty: "MEDIUM", prompt: "ما اسم طريق التجارة القديم الذي ربط الصين بحوض البحر المتوسط؟", acceptedAnswers: ["طريق الحرير"] },
  { id: "ar-his-015", category: "HISTORY", difficulty: "MEDIUM", prompt: "من هي ملكة مصر المعروفة بتحالفها مع يوليوس قيصر ومارك أنطوني؟", acceptedAnswers: ["كليوباترا"] },
  { id: "ar-his-016", category: "HISTORY", difficulty: "MEDIUM", prompt: "في أي عام بدأت الحرب العالمية الأولى؟", acceptedAnswers: ["1914"] },
  { id: "ar-his-017", category: "HISTORY", difficulty: "MEDIUM", prompt: "أي إمبراطورية حكمها السلطان سليمان القانوني في أوج عظمتها؟", acceptedAnswers: ["الدولة العثمانية", "العثمانية"] },
  { id: "ar-his-018", category: "HISTORY", difficulty: "MEDIUM", prompt: "ما هو المعلم الفرنسي الذي بُني لمعرض عالمي وأصبح رمزاً عالمياً؟", acceptedAnswers: ["برج إيفل"] },
  { id: "ar-his-019", category: "HISTORY", difficulty: "MEDIUM", prompt: "أي مستكشف قاد أول رحلة بحرية للدوران حول العالم؟", acceptedAnswers: ["ماجلان", "فرديناند ماجلان"] },
  { id: "ar-his-020", category: "HISTORY", difficulty: "MEDIUM", prompt: "ما اسم المعاهدة التي أنهت رسمياً الحرب العالمية الأولى؟", acceptedAnswers: ["معاهدة فرساي"] },
  { id: "ar-his-021", category: "HISTORY", difficulty: "HARD", prompt: "في أي عام بدأت الثورة الفرنسية؟", acceptedAnswers: ["1789"] },
  { id: "ar-his-022", category: "HISTORY", difficulty: "HARD", prompt: "من هو القائد المغولي الذي أسس أكبر إمبراطورية برية متصلة في التاريخ؟", acceptedAnswers: ["جنكيز خان"] },
  { id: "ar-his-023", category: "HISTORY", difficulty: "HARD", prompt: "من هو الملك القديم المعروف بأحد أقدم قوانين مكتوبة في التاريخ؟", acceptedAnswers: ["حمورابي"] },
  { id: "ar-his-024", category: "HISTORY", difficulty: "HARD", prompt: "في أي قرن بدأ عصر النهضة الأوروبية؟", acceptedAnswers: ["الرابع عشر", "القرن الرابع عشر"] },
  { id: "ar-his-025", category: "HISTORY", difficulty: "HARD", prompt: "ما اسم الحدث الذي هبط فيه الإنسان على سطح القمر لأول مرة؟", acceptedAnswers: ["أبولو 11", "الهبوط على القمر"] },
  { id: "ar-his-026", category: "HISTORY", difficulty: "EASY", prompt: "ما اسم الحرب التي دارت بين شمال وجنوب الولايات المتحدة؟", acceptedAnswers: ["الحرب الأهلية الأمريكية", "الحرب الأهلية"] },
  { id: "ar-his-027", category: "HISTORY", difficulty: "MEDIUM", prompt: "ما اسم إحدى عجائب الدنيا السبع القديمة التي كانت تمثالاً ضخماً عند مدخل ميناء يوناني؟", acceptedAnswers: ["تمثال رودس", "عملاق رودس"] },
  { id: "ar-his-028", category: "HISTORY", difficulty: "EASY", prompt: "في أي عقد أصبح الإنترنت متاحاً على نطاق واسع للجمهور؟", acceptedAnswers: ["التسعينيات", "التسعينات"] },
  { id: "ar-his-029", category: "HISTORY", difficulty: "MEDIUM", prompt: "ما اسم السفينة التي نقلت الحجاج الأوائل إلى أمريكا عام 1620؟", acceptedAnswers: ["مايفلاور"] },
  { id: "ar-his-030", category: "HISTORY", difficulty: "HARD", prompt: "من هو القائد القرطاجي الشهير الذي عبر جبال الألب بالفيلة لمحاربة روما؟", acceptedAnswers: ["هانيبال"] },
];
