import type { ImpostorWordItem } from "../types";

// Secret words for the Impostor game (Arabic). Everyone except the impostor sees the
// word and its category; the impostor only sees the category, then everyone gives a
// one-word clue in turn. Words are deliberately concrete and table-guessable within a
// restaurant/cafe setting.
export const IMPOSTOR_WORDS: ImpostorWordItem[] = [
  { id: "ar-imp-001", category: "طعام", word: "بيتزا" },
  { id: "ar-imp-002", category: "طعام", word: "سوشي" },
  { id: "ar-imp-003", category: "طعام", word: "برغر" },
  { id: "ar-imp-004", category: "طعام", word: "حمّص" },
  { id: "ar-imp-005", category: "طعام", word: "آيس كريم" },
  { id: "ar-imp-006", category: "طعام", word: "معكرونة" },
  { id: "ar-imp-007", category: "طعام", word: "فلافل" },
  { id: "ar-imp-008", category: "طعام", word: "شوكولاتة" },
  { id: "ar-imp-009", category: "حيوانات", word: "أسد" },
  { id: "ar-imp-010", category: "حيوانات", word: "فيل" },
  { id: "ar-imp-011", category: "حيوانات", word: "بطريق" },
  { id: "ar-imp-012", category: "حيوانات", word: "دولفين" },
  { id: "ar-imp-013", category: "حيوانات", word: "قطة" },
  { id: "ar-imp-014", category: "حيوانات", word: "جمل" },
  { id: "ar-imp-015", category: "حيوانات", word: "نسر" },
  { id: "ar-imp-016", category: "أماكن", word: "شاطئ" },
  { id: "ar-imp-017", category: "أماكن", word: "مطار" },
  { id: "ar-imp-018", category: "أماكن", word: "مستشفى" },
  { id: "ar-imp-019", category: "أماكن", word: "مسجد" },
  { id: "ar-imp-020", category: "أماكن", word: "استاد" },
  { id: "ar-imp-021", category: "أماكن", word: "صحراء" },
  { id: "ar-imp-022", category: "أماكن", word: "مكتبة" },
  { id: "ar-imp-023", category: "أفلام ومسلسلات", word: "تايتانيك" },
  { id: "ar-imp-024", category: "أفلام ومسلسلات", word: "الرجل العنكبوت" },
  { id: "ar-imp-025", category: "أفلام ومسلسلات", word: "فريندز" },
  { id: "ar-imp-026", category: "أفلام ومسلسلات", word: "الأسد الملك" },
  { id: "ar-imp-027", category: "أفلام ومسلسلات", word: "هاري بوتر" },
  { id: "ar-imp-028", category: "أغراض", word: "مظلة" },
  { id: "ar-imp-029", category: "أغراض", word: "مرآة" },
  { id: "ar-imp-030", category: "أغراض", word: "حقيبة ظهر" },
  { id: "ar-imp-031", category: "أغراض", word: "ساعة" },
  { id: "ar-imp-032", category: "أغراض", word: "شمعة" },
  { id: "ar-imp-033", category: "أغراض", word: "هاتف" },
  { id: "ar-imp-034", category: "أغراض", word: "نظارة شمسية" },
  { id: "ar-imp-035", category: "رياضة", word: "كرة القدم" },
  { id: "ar-imp-036", category: "رياضة", word: "كرة السلة" },
  { id: "ar-imp-037", category: "رياضة", word: "سباحة" },
  { id: "ar-imp-038", category: "رياضة", word: "تنس" },
  { id: "ar-imp-039", category: "رياضة", word: "ملاكمة" },
  { id: "ar-imp-040", category: "مهن", word: "طبيب" },
  { id: "ar-imp-041", category: "مهن", word: "طاهٍ" },
  { id: "ar-imp-042", category: "مهن", word: "طيار" },
  { id: "ar-imp-043", category: "مهن", word: "معلم" },
  { id: "ar-imp-044", category: "مهن", word: "نادل" },
  { id: "ar-imp-045", category: "مهن", word: "رجل إطفاء" },
  { id: "ar-imp-046", category: "طقس", word: "عاصفة رعدية" },
  { id: "ar-imp-047", category: "طقس", word: "ثلج" },
  { id: "ar-imp-048", category: "طقس", word: "قوس قزح" },
  { id: "ar-imp-049", category: "طقس", word: "موجة حر" },
  { id: "ar-imp-050", category: "طقس", word: "ضباب" },
];
