import type { TriviaContentItem } from "../types";

export const SCIENCE: TriviaContentItem[] = [
  { id: "ar-sci-001", category: "SCIENCE", difficulty: "EASY", prompt: "ما هو الكوكب المعروف باسم 'الكوكب الأحمر'؟", acceptedAnswers: ["المريخ"] },
  { id: "ar-sci-002", category: "SCIENCE", difficulty: "EASY", prompt: "ما هو الغاز الذي يحتاجه الإنسان للتنفس؟", acceptedAnswers: ["الأكسجين", "أكسجين"] },
  { id: "ar-sci-003", category: "SCIENCE", difficulty: "EASY", prompt: "ما هو الرمز الكيميائي للماء؟", acceptedAnswers: ["h2o"] },
  { id: "ar-sci-004", category: "SCIENCE", difficulty: "EASY", prompt: "ما هو العضو الذي يضخ الدم في جسم الإنسان؟", acceptedAnswers: ["القلب"] },
  { id: "ar-sci-005", category: "SCIENCE", difficulty: "EASY", prompt: "كم عدد كواكب مجموعتنا الشمسية؟", acceptedAnswers: ["8", "ثمانية"] },
  { id: "ar-sci-006", category: "SCIENCE", difficulty: "EASY", prompt: "ما هي القوة التي تجذب الأجسام نحو الأرض؟", acceptedAnswers: ["الجاذبية"] },
  { id: "ar-sci-007", category: "SCIENCE", difficulty: "EASY", prompt: "ماذا نسمي الحيوان الذي يتغذى على النباتات فقط؟", acceptedAnswers: ["عاشب", "آكل الأعشاب"] },
  { id: "ar-sci-008", category: "SCIENCE", difficulty: "EASY", prompt: "ما هو النجم الذي يقع في مركز مجموعتنا الشمسية؟", acceptedAnswers: ["الشمس"] },
  { id: "ar-sci-009", category: "SCIENCE", difficulty: "EASY", prompt: "ما هو أقرب كوكب إلى الشمس؟", acceptedAnswers: ["عطارد"] },
  { id: "ar-sci-010", category: "SCIENCE", difficulty: "EASY", prompt: "ما هو العضو الذي نستخدمه للرؤية؟", acceptedAnswers: ["العين", "العينان"] },
  { id: "ar-sci-011", category: "SCIENCE", difficulty: "MEDIUM", prompt: "ما هو الرمز الكيميائي للذهب؟", acceptedAnswers: ["au"] },
  { id: "ar-sci-012", category: "SCIENCE", difficulty: "MEDIUM", prompt: "ما اسم العملية التي تصنع بها النباتات غذاءها؟", acceptedAnswers: ["التمثيل الضوئي", "البناء الضوئي"] },
  { id: "ar-sci-013", category: "SCIENCE", difficulty: "MEDIUM", prompt: "ما هي درجة غليان الماء بالمئوية؟", acceptedAnswers: ["100", "مئة"] },
  { id: "ar-sci-014", category: "SCIENCE", difficulty: "MEDIUM", prompt: "من صاحب نظرية التطور بالانتخاب الطبيعي؟", acceptedAnswers: ["تشارلز داروين", "داروين"] },
  { id: "ar-sci-015", category: "SCIENCE", difficulty: "MEDIUM", prompt: "ما اسم مركز إنتاج الطاقة داخل الخلية؟", acceptedAnswers: ["الميتوكندريا", "الميتوكوندريا"] },
  { id: "ar-sci-016", category: "SCIENCE", difficulty: "MEDIUM", prompt: "ما اسم العلم الذي يدرس الكائنات الحية؟", acceptedAnswers: ["علم الأحياء", "الأحياء"] },
  { id: "ar-sci-017", category: "SCIENCE", difficulty: "MEDIUM", prompt: "أي غاز تمتصه النباتات من الغلاف الجوي؟", acceptedAnswers: ["ثاني أكسيد الكربون"] },
  { id: "ar-sci-018", category: "SCIENCE", difficulty: "MEDIUM", prompt: "ما هي درجة تجمد الماء بالفهرنهايت؟", acceptedAnswers: ["32"] },
  { id: "ar-sci-019", category: "SCIENCE", difficulty: "MEDIUM", prompt: "ما نوع الطاقة المخزنة في البطارية؟", acceptedAnswers: ["طاقة كيميائية", "كيميائية"] },
  { id: "ar-sci-020", category: "SCIENCE", difficulty: "MEDIUM", prompt: "ما اسم الجهاز المستخدم لقياس الزلازل؟", acceptedAnswers: ["مقياس الزلازل", "السيزموغراف"] },
  { id: "ar-sci-021", category: "SCIENCE", difficulty: "HARD", prompt: "من صاحب نظرية النسبية العامة؟", acceptedAnswers: ["ألبرت أينشتاين", "أينشتاين"] },
  { id: "ar-sci-022", category: "SCIENCE", difficulty: "HARD", prompt: "ما هو الرمز الكيميائي للصوديوم؟", acceptedAnswers: ["na"] },
  { id: "ar-sci-023", category: "SCIENCE", difficulty: "HARD", prompt: "ما اسم الجسيم الذي يحمل شحنة سالبة داخل الذرة؟", acceptedAnswers: ["الإلكترون", "إلكترون"] },
  { id: "ar-sci-024", category: "SCIENCE", difficulty: "HARD", prompt: "ما اسم المجرة التي تحتوي على مجموعتنا الشمسية؟", acceptedAnswers: ["درب التبانة"] },
  { id: "ar-sci-025", category: "SCIENCE", difficulty: "HARD", prompt: "ما هو الكوكب الوحيد في مجموعتنا الشمسية الذي يدور على جنبه؟", acceptedAnswers: ["أورانوس"] },
  { id: "ar-sci-026", category: "SCIENCE", difficulty: "EASY", prompt: "ماذا نسمي العالم الذي يدرس الفضاء؟", acceptedAnswers: ["فلكي", "عالم فلك"] },
  { id: "ar-sci-027", category: "SCIENCE", difficulty: "MEDIUM", prompt: "ما هي أصلب مادة طبيعية على الأرض؟", acceptedAnswers: ["الماس", "الألماس"] },
  { id: "ar-sci-028", category: "SCIENCE", difficulty: "MEDIUM", prompt: "أي فيتامين تساعد أشعة الشمس الجسم على إنتاجه؟", acceptedAnswers: ["فيتامين د"] },
  { id: "ar-sci-029", category: "SCIENCE", difficulty: "EASY", prompt: "ما هو الغاز الذي تنتجه النباتات أثناء التمثيل الضوئي ويحتاجه الإنسان؟", acceptedAnswers: ["الأكسجين"] },
  { id: "ar-sci-030", category: "SCIENCE", difficulty: "HARD", prompt: "ما هي سرعة الضوء تقريباً في الفراغ بالكيلومتر في الثانية؟", acceptedAnswers: ["300000"] },
];
