import type { TriviaContentItem } from "../types";

export const SPORTS: TriviaContentItem[] = [
  { id: "ar-spo-001", category: "SPORTS", difficulty: "EASY", prompt: "كم عدد لاعبي فريق كرة القدم داخل الملعب لكل فريق؟", acceptedAnswers: ["11", "أحد عشر", "احد عشر"] },
  { id: "ar-spo-002", category: "SPORTS", difficulty: "EASY", prompt: "أي منتخب فاز بكأس العالم لكرة القدم عام 2022؟", acceptedAnswers: ["الأرجنتين", "الارجنتين"] },
  { id: "ar-spo-003", category: "SPORTS", difficulty: "EASY", prompt: "كم عدد حلقات العلم الأولمبي؟", acceptedAnswers: ["5", "خمس", "خمسة"] },
  { id: "ar-spo-004", category: "SPORTS", difficulty: "EASY", prompt: "ما هي الرياضة التي تُقام في بطولة ويمبلدون؟", acceptedAnswers: ["التنس"] },
  { id: "ar-spo-005", category: "SPORTS", difficulty: "EASY", prompt: "اذكر نادياً يلعب في الدوري الإسباني.", acceptedAnswers: ["ريال مدريد", "برشلونة", "أتلتيكو مدريد", "اشبيلية", "فالنسيا"] },
  { id: "ar-spo-006", category: "SPORTS", difficulty: "EASY", prompt: "كم عدد لاعبي فريق كرة السلة داخل الملعب؟", acceptedAnswers: ["5", "خمسة"] },
  { id: "ar-spo-007", category: "SPORTS", difficulty: "EASY", prompt: "ما هي الرياضة التي تُلعب باستخدام مضرب وريشة؟", acceptedAnswers: ["الريشة الطائرة", "تنس الريشة", "البادمنتون"] },
  { id: "ar-spo-008", category: "SPORTS", difficulty: "EASY", prompt: "ما هي الرياضة التي تُقام فيها بطولة رولان غاروس؟", acceptedAnswers: ["التنس"] },
  { id: "ar-spo-009", category: "SPORTS", difficulty: "EASY", prompt: "ما اللون الذي يُظهره الحكم للاعب عند طرده من المباراة؟", acceptedAnswers: ["الأحمر", "احمر"] },
  { id: "ar-spo-010", category: "SPORTS", difficulty: "EASY", prompt: "كم عدد لاعبي فريق الكرة الطائرة داخل الملعب؟", acceptedAnswers: ["6", "ستة"] },
  { id: "ar-spo-011", category: "SPORTS", difficulty: "MEDIUM", prompt: "أي منتخب فاز بأكبر عدد من كؤوس العالم لكرة القدم؟", acceptedAnswers: ["البرازيل"] },
  { id: "ar-spo-012", category: "SPORTS", difficulty: "MEDIUM", prompt: "اذكر نادي كرة سلة أمريكياً مقره ولاية كاليفورنيا.", acceptedAnswers: ["ليكرز", "لوس أنجلوس ليكرز", "كليبرز", "ووريورز", "غولدن ستيت ووريورز"] },
  { id: "ar-spo-013", category: "SPORTS", difficulty: "MEDIUM", prompt: "كم عدد الحفر في جولة الغولف القياسية؟", acceptedAnswers: ["18", "ثمانية عشر"] },
  { id: "ar-spo-014", category: "SPORTS", difficulty: "MEDIUM", prompt: "اذكر إحدى بطولات الجراند سلام في التنس.", acceptedAnswers: ["ويمبلدون", "أمريكا المفتوحة", "فرنسا المفتوحة", "أستراليا المفتوحة"] },
  { id: "ar-spo-015", category: "SPORTS", difficulty: "MEDIUM", prompt: "في أي رياضة تُنفذ حركة 'سلام دانك'؟", acceptedAnswers: ["كرة السلة"] },
  { id: "ar-spo-016", category: "SPORTS", difficulty: "MEDIUM", prompt: "كم عدد لاعبي فريق الكريكيت داخل الملعب؟", acceptedAnswers: ["11", "أحد عشر", "احد عشر"] },
  { id: "ar-spo-017", category: "SPORTS", difficulty: "MEDIUM", prompt: "ما هي الرياضة التي تُعرف باسم 'العلم اللطيف'؟", acceptedAnswers: ["الملاكمة"] },
  { id: "ar-spo-018", category: "SPORTS", difficulty: "MEDIUM", prompt: "اذكر رياضة تُقام في الألعاب الأولمبية الصيفية.", acceptedAnswers: ["السباحة", "ألعاب القوى", "كرة السلة", "كرة القدم", "الكرة الطائرة", "الجمباز", "الملاكمة", "الدراجات", "التنس", "المصارعة"] },
  { id: "ar-spo-019", category: "SPORTS", difficulty: "MEDIUM", prompt: "كم عدد أشواط المباراة في الملاكمة الاحترافية عادةً؟", acceptedAnswers: ["12", "اثنا عشر"] },
  { id: "ar-spo-020", category: "SPORTS", difficulty: "MEDIUM", prompt: "ما هي الرياضة التي يُقام فيها سباق تور دو فرانس؟", acceptedAnswers: ["الدراجات", "ركوب الدراجات"] },
  { id: "ar-spo-021", category: "SPORTS", difficulty: "HARD", prompt: "من صاحب الرقم القياسي في عدد بطولات العالم لسباقات الفورمولا 1 حتى عام 2023؟", acceptedAnswers: ["مايكل شوماخر", "لويس هاميلتون", "شوماخر", "هاميلتون"] },
  { id: "ar-spo-022", category: "SPORTS", difficulty: "HARD", prompt: "في أي دولة أُقيمت الألعاب الأولمبية الصيفية عام 2016؟", acceptedAnswers: ["البرازيل"] },
  { id: "ar-spo-023", category: "SPORTS", difficulty: "HARD", prompt: "أي دولة تُعتبر مهد رياضة الرغبي؟", acceptedAnswers: ["إنجلترا", "انجلترا"] },
  { id: "ar-spo-024", category: "SPORTS", difficulty: "HARD", prompt: "كم عدد لاعبي فريق الرغبي داخل الملعب؟", acceptedAnswers: ["15", "خمسة عشر"] },
  { id: "ar-spo-025", category: "SPORTS", difficulty: "HARD", prompt: "أي نادٍ فاز بأكبر عدد من ألقاب دوري أبطال أوروبا؟", acceptedAnswers: ["ريال مدريد"] },
  { id: "ar-spo-026", category: "SPORTS", difficulty: "EASY", prompt: "ماذا نسمي المباراة التي تنتهي بالتعادل دون أهداف؟", acceptedAnswers: ["تعادل سلبي", "تعادل"] },
  { id: "ar-spo-027", category: "SPORTS", difficulty: "MEDIUM", prompt: "كم عدد دقائق مباراة كرة القدم القياسية بدون الوقت الإضافي؟", acceptedAnswers: ["90", "تسعون"] },
  { id: "ar-spo-028", category: "SPORTS", difficulty: "EASY", prompt: "ما هي الرياضة الوطنية لليابان؟", acceptedAnswers: ["السومو", "مصارعة السومو"] },
  { id: "ar-spo-029", category: "SPORTS", difficulty: "MEDIUM", prompt: "كم عدد الأشواط في مباراة كرة السلة الاحترافية؟", acceptedAnswers: ["4", "أربعة"] },
  { id: "ar-spo-030", category: "SPORTS", difficulty: "MEDIUM", prompt: "ما اسم الطوق الذي يجب تسديد الكرة فيه في كرة السلة؟", acceptedAnswers: ["السلة"] },
  { id: "ar-spo-031", category: "SPORTS", difficulty: "EASY", prompt: "أي رياضة تُلعب في بطولة الأمم الأوروبية 'يورو'؟", acceptedAnswers: ["كرة القدم"] },
  { id: "ar-spo-032", category: "SPORTS", difficulty: "HARD", prompt: "كم يبلغ طول سباق الماراثون تقريباً بالكيلومترات؟", acceptedAnswers: ["42", "42.2"] },
];
